import type { Locale } from "./site";

type FunctionGroup = { title: string; description: string; items: string[] };
export type FunctionPageContent = { eyebrow: string; intro: string; groups: FunctionGroup[]; closing: string };

// Descrive solo strumenti effettivamente presenti nell'area riservata.
// Non include la generazione di immagini: l'utente può caricare immagini create esternamente.
export const functionPageContent: Record<Locale, FunctionPageContent> = {
  it: {
    eyebrow: "IL PERCORSO EDITORIALE COMPLETO", intro: "Scrittore Site non è una semplice chat: organizza il lavoro dal progetto iniziale fino ai file da rivedere e pubblicare. Puoi sempre intervenire sui testi e sulle scelte editoriali.", closing: "Ogni controllo è un aiuto editoriale, non una certificazione legale o una garanzia di pubblicazione.", groups: [
      { title: "1. Dall'idea al progetto", description: "Definisci il libro prima di generare contenuti.", items: ["Chat della nicchia: ragiona con te su mercato, lettore e posizionamento e prepara un prompt da copiare manualmente.", "Chat guidata: fa domande mirate, chiede sempre se desideri personalizzare il libro e prepara una proposta compatibile con i campi della sidebar.", "Compilazione assistita: dopo la tua conferma, la proposta della chat può trasferire i valori nella sidebar.", "Sidebar editoriale: titolo, autore, lingua, genere, stile, lettore, obiettivo, limiti e istruzioni personali guidano le operazioni successive."] },
      { title: "2. Fonti, indice e pianificazione", description: "Costruisci una struttura proporzionata al libro che vuoi realizzare.", items: ["Ricerca fonti web quando utile, con registro visibile dei riferimenti selezionati.", "Indice professionale con prefazione, capitoli, sottocapitoli e conclusione; puoi valutarlo, correggerlo e rigenerarlo senza perdere il controllo del progetto.", "Lunghezza Compatto, Standard KDP o Approfondito: l'indice tenta di rispettare sezioni e pagine previste senza aggiungere riempitivi.", "Preventivo prima delle operazioni e scelta tra GPT-5.4 e DeepSeek V4 Pro in base alle funzioni disponibili e ai crediti."] },
      { title: "3. Stesura con memoria editoriale", description: "Scrivi una parte o l'intero manoscritto mantenendo il filo del progetto.", items: ["Scrivi una sezione, i sottocapitoli di un capitolo oppure tutte le sezioni ancora vuote del libro.", "Pausa, stop e ripresa della stesura: il lavoro completato rimane disponibile e la stesura continua dalle sezioni restanti.", "Checkpoint opzionali per aggiungere un'indicazione prima di una Parte o della conclusione.", "Memoria editoriale: riepiloga progetto, temi già trattati, scelte e contenuti salvati per ridurre incoerenze e ripetizioni.", "Editor manuale e rielaborazione mirata: puoi riscrivere o modificare ogni testo; le modifiche dell'utente restano modificabili e salvabili."] },
      { title: "4. Formati e contenuti pratici", description: "Adatta la stesura al genere e al risultato promesso al lettore.", items: ["Quiz, esempi, ricette e contenuti Test Prep con domande, esercizi e soluzioni quando sono coerenti con il progetto.", "Controllo dei fatti, report sintattico e rielaborazione con istruzioni specifiche per le sezioni da migliorare.", "Anteprima del manoscritto, lettore vocale e inserimento di immagini create esternamente nelle sezioni, nel Word e nel PDF."] },
      { title: "5. Revisione, originalità e KDP", description: "Controlla il manoscritto prima dell'esportazione.", items: ["Controllo di completezza e coerenza tra indice, sezioni e contenuti promessi.", "Controllo locale di originalità confrontato solo con PDF e DOCX caricati dall'utente.", "Controllo copyright web completo con GPT, da leggere come supporto editoriale e non come parere legale.", "Checklist di conformità alle linee guida KDP: evidenzia elementi da verificare prima del caricamento su Amazon."] },
      { title: "6. Salvataggio, recupero ed export", description: "Mantieni il progetto disponibile anche dopo una pausa di lavoro.", items: ["Salva sessione conserva sidebar, indice, sezioni, fonti e modifiche nel tuo account.", "Riaggiorna all'ultima stesura ripristina il progetto salvato dopo nuovo accesso o aggiornamento della pagina.", "Esporta e importa CSV per una copia completa e portabile del progetto editoriale.", "Scarica Word o PDF dopo la revisione finale; il reset progetto elimina intenzionalmente tutti i dati del progetto corrente."] },
    ]
  },
  en: {
    eyebrow: "THE COMPLETE EDITORIAL WORKFLOW", intro: "Scrittore Site is not just a chat: it organizes your work from the first idea to files ready for review and publication. You can always edit the text and editorial choices.", closing: "Every check is editorial support, not legal certification or a guarantee of publication.", groups: [
      { title: "1. From idea to project", description: "Define the book before generating content.", items: ["Niche chat: discuss market, reader and positioning, then receive a prompt to copy manually.", "Guided chat: asks focused questions, always asks whether you want to personalize the book, and prepares a proposal compatible with the sidebar.", "Assisted completion: after your confirmation, the chat proposal can transfer values to the sidebar.", "Editorial sidebar: title, author, language, genre, style, reader, objective, limits and personal instructions guide later work."] },
      { title: "2. Sources, outline and planning", description: "Build a structure sized for the book you want to create.", items: ["Web-source research when useful, with a visible register of selected references.", "Professional outline with preface, chapters, subsections and conclusion; review, edit or regenerate it while retaining control.", "Compact, Standard KDP or In-depth length: the outline aims for the planned sections and pages without padding.", "An estimate before operations and a choice between GPT-5.4 and DeepSeek V4 Pro based on available features and credits."] },
      { title: "3. Writing with editorial memory", description: "Write one part or the full manuscript while keeping the project consistent.", items: ["Write one section, a chapter's subsections, or every still-empty section in the book.", "Pause, stop and resume writing: completed work remains available and writing continues from remaining sections.", "Optional checkpoints to add an instruction before a Part or the conclusion.", "Editorial memory summarizes the project, covered themes, choices and saved content to reduce inconsistencies and repetition.", "Manual editor and focused rewriting: you can rewrite or edit every text; your changes remain editable and saveable."] },
      { title: "4. Practical formats and content", description: "Match the draft to the genre and outcome promised to the reader.", items: ["Quizzes, examples, recipes and Test Prep material with questions, exercises and solutions when appropriate for the project.", "Fact checking, syntax reports and instruction-based rewriting for sections that need improvement.", "Manuscript preview, voice reader and insertion of externally created images into sections, Word and PDF."] },
      { title: "5. Review, originality and KDP", description: "Review the manuscript before exporting.", items: ["Completeness and consistency check across outline, sections and promised content.", "Local originality check compared only with PDF and DOCX files uploaded by the user.", "Full web copyright check with GPT, to be read as editorial support rather than legal advice.", "KDP-guideline checklist that highlights items to verify before uploading to Amazon."] },
      { title: "6. Save, restore and export", description: "Keep the project available after a break from work.", items: ["Save session keeps the sidebar, outline, sections, sources and edits in your account.", "Refresh the latest draft restores the saved project after logging in again or refreshing the page.", "Export and import CSV for a complete, portable editorial-project backup.", "Download Word or PDF after final review; Reset project intentionally deletes all current-project data."] },
    ]
  },
  es: { eyebrow: "EL RECORRIDO EDITORIAL COMPLETO", intro: "Scrittore Site no es solo un chat: organiza el trabajo desde la idea hasta los archivos que puedes revisar y publicar. Siempre puedes editar textos y decisiones editoriales.", closing: "Cada control es una ayuda editorial, no una certificación legal ni una garantía de publicación.", groups: [
    { title: "1. De la idea al proyecto", description: "Define el libro antes de generar contenido.", items: ["Chat de nicho para razonar sobre mercado, lector y posicionamiento y preparar un prompt para copiar manualmente.", "Chat guiado con preguntas concretas, personalización obligatoria y propuesta compatible con la barra lateral.", "Tras tu confirmación, la propuesta puede transferir valores a la barra lateral.", "La barra editorial reúne título, autor, idioma, género, estilo, lector, objetivo, límites e instrucciones."] },
    { title: "2. Fuentes, índice y planificación", description: "Construye una estructura proporcionada al libro.", items: ["Investigación web cuando sea útil con un registro visible de fuentes.", "Índice profesional con prefacio, capítulos, apartados y conclusión, modificable y regenerable.", "Longitud Compacta, Estándar KDP o Profunda sin añadir relleno.", "Estimación previa y elección entre GPT-5.4 y DeepSeek V4 Pro."] },
    { title: "3. Escritura con memoria editorial", description: "Escribe una parte o todo el manuscrito con coherencia.", items: ["Escribe una sección, los apartados de un capítulo o todas las secciones vacías.", "Pausa, detén y reanuda sin perder el trabajo terminado.", "Puntos de control opcionales antes de una Parte o de la conclusión.", "Memoria editorial para reducir incoherencias y repeticiones.", "Editor manual y reescritura dirigida de cada texto."] },
    { title: "4. Formatos y contenidos prácticos", description: "Adapta el texto al género y al lector.", items: ["Cuestionarios, ejemplos, recetas y Test Prep con preguntas, ejercicios y soluciones cuando correspondan.", "Verificación de hechos, informe sintáctico y reescritura con instrucciones.", "Vista previa, lector de voz e imágenes creadas externamente en secciones, Word y PDF."] },
    { title: "5. Revisión, originalidad y KDP", description: "Comprueba el manuscrito antes de exportarlo.", items: ["Control de completitud y coherencia.", "Control local solo frente a PDF y DOCX cargados por el usuario.", "Control web de copyright con GPT como apoyo editorial, no asesoramiento legal.", "Checklist KDP con elementos por verificar antes de Amazon."] },
    { title: "6. Guardar, recuperar y exportar", description: "Conserva el proyecto entre sesiones.", items: ["Guardar sesión conserva barra lateral, índice, secciones, fuentes y cambios.", "Actualizar el último borrador restaura el proyecto guardado.", "Importar y exportar CSV crea una copia completa y transportable.", "Descarga Word o PDF; Reset elimina intencionalmente todos los datos del proyecto actual."] },
  ] },
  fr: { eyebrow: "LE PARCOURS ÉDITORIAL COMPLET", intro: "Scrittore Site n'est pas un simple chat : il organise le travail de l'idée aux fichiers à relire et publier. Vous pouvez toujours modifier les textes et les choix éditoriaux.", closing: "Chaque contrôle est une aide éditoriale, non une certification juridique ni une garantie de publication.", groups: [
    { title: "1. De l'idée au projet", description: "Définissez le livre avant de générer le contenu.", items: ["Chat de niche pour réfléchir au marché, au lecteur et au positionnement, puis préparer un prompt à copier.", "Chat guidé : questions ciblées, personnalisation demandée et proposition compatible avec la barre latérale.", "Après votre confirmation, la proposition peut remplir la barre latérale.", "Brief éditorial : titre, auteur, langue, genre, style, lecteur, objectif, limites et instructions."] },
    { title: "2. Sources, plan et préparation", description: "Construisez une structure proportionnée au livre.", items: ["Recherche web utile avec registre visible des sources.", "Plan professionnel avec préface, chapitres, sous-parties et conclusion, modifiable et régénérable.", "Format Compact, Standard KDP ou Approfondi sans remplissage.", "Estimation avant action et choix entre GPT-5.4 et DeepSeek V4 Pro."] },
    { title: "3. Rédaction avec mémoire éditoriale", description: "Rédigez une partie ou tout le manuscrit de façon cohérente.", items: ["Rédigez une section, les sous-parties d'un chapitre ou toutes les sections vides.", "Pause, arrêt et reprise sans perdre le travail terminé.", "Points de contrôle facultatifs avant une Partie ou la conclusion.", "Mémoire éditoriale pour limiter incohérences et répétitions.", "Éditeur manuel et réécriture ciblée de chaque texte."] },
    { title: "4. Formats et contenus pratiques", description: "Adaptez le texte au genre et au lecteur.", items: ["Quiz, exemples, recettes et Test Prep avec questions, exercices et solutions lorsque pertinents.", "Vérification des faits, rapport syntaxique et réécriture avec consigne.", "Aperçu, lecteur vocal et images créées à l'extérieur dans les sections, Word et PDF."] },
    { title: "5. Révision, originalité et KDP", description: "Vérifiez le manuscrit avant l'export.", items: ["Contrôle de complétude et cohérence.", "Contrôle local uniquement avec les PDF et DOCX chargés.", "Contrôle copyright web GPT : soutien éditorial, pas avis juridique.", "Checklist KDP avant l'envoi sur Amazon."] },
    { title: "6. Sauvegarder, restaurer et exporter", description: "Gardez le projet entre les sessions.", items: ["La sauvegarde conserve barre latérale, plan, sections, sources et modifications.", "Actualiser la dernière version restaure le projet sauvegardé.", "Import/export CSV pour une copie complète et portable.", "Téléchargez Word ou PDF ; Reset supprime volontairement le projet actuel."] },
  ] },
  de: { eyebrow: "DER VOLLSTÄNDIGE REDAKTIONELLE WEG", intro: "Scrittore Site ist nicht nur ein Chat: Es organisiert die Arbeit von der Idee bis zu Dateien für Prüfung und Veröffentlichung. Texte und redaktionelle Entscheidungen bleiben jederzeit änderbar.", closing: "Jede Prüfung ist redaktionelle Hilfe, keine Rechtszertifizierung oder Veröffentlichungsgarantie.", groups: [
    { title: "1. Von der Idee zum Projekt", description: "Definieren Sie das Buch vor der Inhaltserstellung.", items: ["Nischen-Chat für Markt, Leser und Positionierung mit einem manuell kopierbaren Prompt.", "Geführter Chat mit gezielten Fragen, Personalisierung und sidebar-kompatiblem Vorschlag.", "Nach Ihrer Bestätigung kann der Vorschlag die Seitenleiste füllen.", "Editoriale Sidebar für Titel, Autor, Sprache, Genre, Stil, Leser, Ziel, Grenzen und Anweisungen."] },
    { title: "2. Quellen, Gliederung und Planung", description: "Erstellen Sie eine passende Buchstruktur.", items: ["Webrecherche bei Bedarf mit sichtbarem Quellenregister.", "Professionelle Gliederung mit Vorwort, Kapiteln, Unterkapiteln und Schluss; bearbeitbar und neu erstellbar.", "Kompakt, Standard KDP oder Vertieft ohne Füllmaterial.", "Kostenschätzung und Wahl zwischen GPT-5.4 und DeepSeek V4 Pro."] },
    { title: "3. Schreiben mit redaktionellem Gedächtnis", description: "Schreiben Sie Teile oder das gesamte Manuskript konsistent.", items: ["Einen Abschnitt, Kapitelunterabschnitte oder alle leeren Abschnitte schreiben.", "Pausieren, stoppen und fortsetzen ohne fertige Arbeit zu verlieren.", "Optionale Checkpoints vor einem Teil oder dem Schluss.", "Redaktionelles Gedächtnis gegen Inkonsistenzen und Wiederholungen.", "Manueller Editor und gezielte Überarbeitung jedes Textes."] },
    { title: "4. Praktische Formate und Inhalte", description: "Passen Sie den Text an Genre und Leser an.", items: ["Quiz, Beispiele, Rezepte und Test Prep mit Fragen, Übungen und Lösungen, wenn passend.", "Faktencheck, Syntaxbericht und Überarbeitung mit Anweisung.", "Vorschau, Sprachleser und extern erstellte Bilder in Abschnitten, Word und PDF."] },
    { title: "5. Prüfung, Originalität und KDP", description: "Prüfen Sie das Manuskript vor dem Export.", items: ["Vollständigkeits- und Konsistenzprüfung.", "Lokale Originalitätsprüfung nur gegen hochgeladene PDF und DOCX.", "Web-Copyrightprüfung mit GPT als redaktionelle Hilfe, nicht als Rechtsrat.", "KDP-Checkliste vor dem Amazon-Upload."] },
    { title: "6. Speichern, wiederherstellen und exportieren", description: "Bewahren Sie das Projekt zwischen Sitzungen.", items: ["Sitzung speichern bewahrt Sidebar, Gliederung, Abschnitte, Quellen und Änderungen.", "Letzten Entwurf aktualisieren stellt das gespeicherte Projekt wieder her.", "CSV-Import/-Export für eine vollständige transportable Kopie.", "Word oder PDF herunterladen; Reset löscht bewusst alle Daten des aktuellen Projekts."] },
  ] },
  ro: { eyebrow: "PARCURSUL EDITORIAL COMPLET", intro: "Scrittore Site nu este doar un chat: organizează munca de la idee la fișierele pentru revizuire și publicare. Poți modifica mereu textele și deciziile editoriale.", closing: "Fiecare control este sprijin editorial, nu certificare juridică sau garanție de publicare.", groups: [
    { title: "1. De la idee la proiect", description: "Definește cartea înainte de generare.", items: ["Chat de nișă pentru piață, cititor și poziționare, cu prompt de copiat manual.", "Chat ghidat cu întrebări țintite, personalizare și propunere compatibilă cu bara laterală.", "După confirmare, propunerea poate completa bara laterală.", "Brief editorial: titlu, autor, limbă, gen, stil, cititor, obiectiv, limite și instrucțiuni."] },
    { title: "2. Surse, cuprins și planificare", description: "Construiește structura potrivită cărții.", items: ["Cercetare web când este utilă, cu registru de surse vizibil.", "Cuprins profesional cu prefață, capitole, subcapitole și concluzie, editabil și regenerabil.", "Compact, Standard KDP sau Aprofundat fără umplutură.", "Estimare înainte de operații și alegerea dintre GPT-5.4 și DeepSeek V4 Pro."] },
    { title: "3. Scriere cu memorie editorială", description: "Scrie o parte sau întregul manuscris coerent.", items: ["O secțiune, subcapitolele unui capitol sau toate secțiunile goale.", "Pauză, oprire și reluare fără a pierde munca finalizată.", "Checkpoint-uri opționale înaintea unei Părți sau concluziei.", "Memorie editorială pentru mai puține incoerențe și repetiții.", "Editor manual și rescriere țintită pentru fiecare text."] },
    { title: "4. Formate și conținut practic", description: "Adaptează textul la gen și cititor.", items: ["Quiz-uri, exemple, rețete și Test Prep cu întrebări, exerciții și soluții când sunt potrivite.", "Verificarea faptelor, raport sintactic și rescriere cu instrucțiuni.", "Previzualizare, cititor vocal și imagini create extern în secțiuni, Word și PDF."] },
    { title: "5. Revizuire, originalitate și KDP", description: "Verifică manuscrisul înainte de export.", items: ["Control de completitudine și coerență.", "Control local numai cu PDF și DOCX încărcate de utilizator.", "Control web de copyright cu GPT ca ajutor editorial, nu sfat juridic.", "Checklist KDP înainte de încărcarea pe Amazon."] },
    { title: "6. Salvare, restaurare și export", description: "Păstrează proiectul între sesiuni.", items: ["Salvarea sesiunii păstrează bara laterală, cuprinsul, secțiunile, sursele și modificările.", "Actualizarea ultimei versiuni restaurează proiectul salvat.", "Import/export CSV pentru copie completă și portabilă.", "Descarcă Word sau PDF; Reset șterge intenționat proiectul curent."] },
  ] },
  ru: { eyebrow: "ПОЛНЫЙ РЕДАКЦИОННЫЙ ПУТЬ", intro: "Scrittore Site — не просто чат: он организует работу от идеи до файлов для проверки и публикации. Тексты и редакторские решения всегда можно изменить.", closing: "Каждая проверка — редакторская поддержка, а не юридическая сертификация или гарантия публикации.", groups: [
    { title: "1. От идеи к проекту", description: "Определите книгу до создания текста.", items: ["Чат ниши для обсуждения рынка, читателя и позиционирования с готовым промптом для копирования.", "Гид-чат с точными вопросами, персонализацией и предложением для боковой панели.", "После подтверждения предложение может заполнить боковую панель.", "Редакционный бриф: название, автор, язык, жанр, стиль, читатель, цель, ограничения и инструкции."] },
    { title: "2. Источники, оглавление и план", description: "Создайте структуру, подходящую книге.", items: ["Веб-исследование при необходимости с видимым реестром источников.", "Профессиональное оглавление с предисловием, главами, подразделами и заключением; его можно менять и создавать заново.", "Компактный, стандартный KDP или расширенный формат без наполнителя.", "Предварительная оценка и выбор GPT-5.4 или DeepSeek V4 Pro."] },
    { title: "3. Написание с редакционной памятью", description: "Пишите часть или всю рукопись последовательно.", items: ["Раздел, подразделы главы или все пустые разделы книги.", "Пауза, остановка и продолжение без потери готовой работы.", "Необязательные контрольные точки перед частью или заключением.", "Редакционная память уменьшает несоответствия и повторы.", "Ручной редактор и адресная переработка каждого текста."] },
    { title: "4. Практические форматы и содержание", description: "Адаптируйте текст к жанру и читателю.", items: ["Тесты, примеры, рецепты и Test Prep с вопросами, упражнениями и решениями при необходимости.", "Проверка фактов, синтаксический отчёт и переработка по инструкции.", "Предпросмотр, голосовое чтение и внешние изображения в разделах, Word и PDF."] },
    { title: "5. Проверка, оригинальность и KDP", description: "Проверьте рукопись перед экспортом.", items: ["Проверка полноты и согласованности.", "Локальная проверка только по загруженным пользователем PDF и DOCX.", "Веб-проверка copyright с GPT как редакторская помощь, не юридическая консультация.", "Чек-лист KDP перед загрузкой на Amazon."] },
    { title: "6. Сохранение, восстановление и экспорт", description: "Сохраняйте проект между сессиями.", items: ["Сохранение сессии хранит боковую панель, оглавление, разделы, источники и правки.", "Обновление последней версии восстанавливает сохранённый проект.", "Импорт/экспорт CSV для полной переносимой копии.", "Скачайте Word или PDF; Reset намеренно удаляет текущий проект."] },
  ] },
  ar: { eyebrow: "مسار التحرير الكامل", intro: "Scrittore Site ليس مجرد محادثة: فهو ينظم العمل من الفكرة إلى الملفات الجاهزة للمراجعة والنشر. يمكنك دائماً تعديل النصوص والاختيارات التحريرية.", closing: "كل فحص هو دعم تحريري، وليس شهادة قانونية أو ضماناً للنشر.", groups: [
    { title: "1. من الفكرة إلى المشروع", description: "حدّد الكتاب قبل إنشاء المحتوى.", items: ["محادثة التخصص لمناقشة السوق والقارئ والتموضع وإعداد مطالبة تنسخ يدوياً.", "المحادثة الموجهة بأسئلة مركزة وتخصيص ومقترح متوافق مع الشريط الجانبي.", "بعد التأكيد يمكن للمقترح ملء الشريط الجانبي.", "موجز تحريري للعنوان والمؤلف واللغة والنوع والأسلوب والقارئ والهدف والحدود والتعليمات."] },
    { title: "2. المصادر والفهرس والتخطيط", description: "ابنِ بنية تناسب الكتاب.", items: ["بحث ويب عند الحاجة مع سجل مصادر ظاهر.", "فهرس احترافي بمقدمة وفصول وأقسام فرعية وخاتمة قابل للتعديل وإعادة الإنشاء.", "مختصر أو Standard KDP أو متعمق بلا حشو.", "تقدير مسبق واختيار بين GPT-5.4 وDeepSeek V4 Pro."] },
    { title: "3. الكتابة مع ذاكرة تحريرية", description: "اكتب جزءاً أو المخطوطة كاملة بتناسق.", items: ["قسم واحد أو أقسام فصل فرعية أو كل الأقسام الفارغة.", "إيقاف مؤقت وتوقف واستئناف من دون فقد العمل المكتمل.", "نقاط تحقق اختيارية قبل جزء أو الخاتمة.", "ذاكرة تحريرية للحد من التناقض والتكرار.", "محرر يدوي وإعادة صياغة موجهة لكل نص."] },
    { title: "4. صيغ ومحتوى عملي", description: "كيّف النص مع النوع والقارئ.", items: ["اختبارات وأمثلة ووصفات وTest Prep بأسئلة وتمارين وحلول عند الملاءمة.", "تحقق من الحقائق وتقرير نحوي وإعادة صياغة بتعليمات.", "معاينة وقارئ صوتي وصور منشأة خارجياً في الأقسام وWord وPDF."] },
    { title: "5. المراجعة والأصالة وKDP", description: "افحص المخطوطة قبل التصدير.", items: ["فحص الاكتمال والتناسق.", "فحص محلي فقط مع ملفات PDF وDOCX المحمّلة.", "فحص copyright عبر الويب بـGPT كدعم تحريري وليس نصيحة قانونية.", "قائمة KDP قبل الرفع إلى Amazon."] },
    { title: "6. الحفظ والاستعادة والتصدير", description: "احتفظ بالمشروع بين الجلسات.", items: ["حفظ الجلسة يحفظ الشريط والفهرس والأقسام والمصادر والتعديلات.", "تحديث آخر مسودة يستعيد المشروع المحفوظ.", "استيراد وتصدير CSV لنسخة كاملة قابلة للنقل.", "نزّل Word أو PDF؛ Reset يحذف المشروع الحالي عمداً."] },
  ] },
  zh: { eyebrow: "完整编辑工作流", intro: "Scrittore Site 不只是聊天工具：它将工作从想法组织到可审阅和发布的文件。您始终可以修改文本和编辑选择。", closing: "每项检查都是编辑辅助，而非法律认证或出版保证。", groups: [
    { title: "1. 从想法到项目", description: "在生成内容前定义图书。", items: ["细分市场聊天：讨论市场、读者和定位，并生成可手动复制的提示词。", "引导式聊天：提出聚焦问题、要求个性化，并准备与侧栏兼容的建议。", "确认后，建议可填写侧栏字段。", "编辑侧栏包括标题、作者、语言、体裁、风格、读者、目标、限制和说明。"] },
    { title: "2. 来源、目录与规划", description: "建立适合图书的结构。", items: ["在需要时进行网络研究，并显示来源登记。", "专业目录包含前言、章节、小节和结论，可修改或重新生成。", "紧凑、Standard KDP 或深入长度，不添加填充内容。", "操作前预估，并在 GPT-5.4 与 DeepSeek V4 Pro 间选择。"] },
    { title: "3. 带编辑记忆的写作", description: "连贯地写一个部分或整部手稿。", items: ["撰写一个章节、一个章节的小节或所有空白部分。", "暂停、停止和继续，已完成工作不会丢失。", "在一个部分或结论前可选的检查点。", "编辑记忆减少不一致和重复。", "手动编辑器和每段文本的定向改写。"] },
    { title: "4. 实用格式和内容", description: "让文本匹配体裁与读者。", items: ["适用时提供测验、示例、食谱和含问题、练习及答案的 Test Prep。", "事实检查、句法报告和按指令改写。", "手稿预览、语音阅读器，以及在章节、Word 和 PDF 中插入外部创建的图片。"] },
    { title: "5. 审阅、原创性与 KDP", description: "导出前检查手稿。", items: ["完整性和一致性检查。", "本地原创性检查仅比较用户上传的 PDF 和 DOCX。", "使用 GPT 的网络版权检查是编辑辅助，不是法律建议。", "上传 Amazon 前的 KDP 清单。"] },
    { title: "6. 保存、恢复与导出", description: "在会话之间保留项目。", items: ["保存会话会保留侧栏、目录、章节、来源和修改。", "刷新最新草稿会恢复已保存项目。", "导入和导出 CSV 以获得完整可移植的副本。", "下载 Word 或 PDF；Reset 会有意删除当前项目。"] },
  ] },
};
