import { resources, type ResourceGuide } from "./resources";
import type { Locale } from "./site";

type Seed = [title: string, description: string, intro: string, focus: string];
type ResourceUi = { nav: string; eyebrow: string; indexTitle: string; indexLead: string; start: string; practice: string; practiceText: string; steps: string[]; faqQuestion: string; faqAnswer: string; read: string; begin: string; all: string; continue: string; other: string; ctaTitle: string; ctaText: string };

const seeds: Record<Exclude<Locale, "it">, Record<string, Seed>> = {
  en: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["How to write a book with artificial intelligence", "A practical guide to turning an idea into a complete editorial project with Scrittore Site.", "Use AI as editorial support, not as autopilot: begin with a clear reader, purpose and structure.", "Set the expected reader outcome first, then review every generated section in the editor before exporting."],
    "come-compilare-sidebar-scrittore-site": ["How to complete the Scrittore Site sidebar", "Clear instructions for configuring the brief behind a consistent outline and manuscript.", "The sidebar turns your idea into editorial instructions used throughout the project.", "Choose language, genre, voice, audience, scope and constraints before generating the outline."],
    "creare-indice-professionale-libro": ["How to create a professional book outline", "Learn to build, assess and improve an outline without repetitive or off-topic chapters.", "A strong outline gives readers a logical path and gives every section a distinct job.", "Keep only essential topics, merge overlaps and check that the final chapter fulfils the book's promise."],
    "fonti-web-originalita-copyright-libro": ["Web sources, originality and copyright", "Use sources and originality checks responsibly when planning a manuscript.", "Sources help you understand a topic; they should never be copied into a new manuscript.", "Review factual claims, permissions and similarity alerts yourself before publication."],
    "scrivere-capitoli-e-sottocapitoli": ["How to write chapters and subsections", "Write, revise and improve sections while keeping the manuscript coherent.", "Each chapter needs one clear task and a conclusion that moves the reader forward.", "Generate with a specific request, make small edits in the editor and use AI revision only for substantial changes."],
    "controllare-manoscritto-prima-pubblicazione": ["How to review a manuscript before publishing", "A practical checklist for completeness, coherence, preview and human revision.", "Generating a manuscript is not the same as preparing it for publication.", "Compare the outline and manuscript, read beginnings and endings, and resolve every meaningful warning."],
    "salvare-ripristinare-esportare-progetto-editoriale": ["How to save, restore and export an editorial project", "Keep the brief, outline, sections and sources safe through saving and export.", "An editorial project includes more than text: it also contains its configuration and history.", "Save after important decisions, keep a CSV backup and use reset only when you truly want to start over."],
    "creare-quiz-ricette-test-prep": ["How to create quizzes, recipes and Test Prep", "Design exercises, questions and practical formats that are useful and verifiable.", "Interactive content must help the reader apply knowledge, not fill empty space.", "State the level, quantity and expected outcome, then check variety, answers and completeness."],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT or DeepSeek: which AI engine for your book?", "A practical comparison of the AI engines, their functions and estimates in Scrittore Site.", "Choose the engine based on the task, available features and the estimate shown before starting.", "A clear brief and focused review matter more than repeated generation with either engine."],
    "pubblicare-libro-amazon-kdp": ["How to prepare a book for Amazon KDP", "Prepare, review and export a manuscript before uploading it to Amazon KDP.", "A readable, complete and checked manuscript comes before formatting and uploading.", "Review rights, data, layout and exported files; always consult Amazon's current official requirements."],
    "self-publishing-guida-pratica": ["Self-publishing: from idea to a ready book", "Organise your brief, manuscript, revision and export for independent publishing.", "Self-publishing keeps the author in charge of creative and publishing decisions.", "Use the outline as a plan, revise the manuscript carefully and preserve every project version."],
  },
  es: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["Cómo escribir un libro con inteligencia artificial", "Guía práctica para transformar una idea en un proyecto editorial completo con Scrittore Site.", "Usa la IA como apoyo editorial y parte de un lector, objetivo y estructura claros.", "Define el resultado para el lector y revisa cada sección generada antes de exportar."],
    "come-compilare-sidebar-scrittore-site": ["Cómo completar la barra lateral de Scrittore Site", "Instrucciones para configurar el brief que guía índice y manuscrito.", "La barra lateral convierte tu idea en instrucciones editoriales coherentes.", "Elige idioma, género, voz, público, alcance y límites antes de generar el índice."],
    "creare-indice-professionale-libro": ["Cómo crear un índice profesional para un libro", "Crea y mejora un índice sin capítulos repetitivos ni temas fuera de lugar.", "Un buen índice crea un recorrido lógico y da una función distinta a cada sección.", "Conserva solo los temas esenciales, une solapamientos y comprueba la promesa final."],
    "fonti-web-originalita-copyright-libro": ["Fuentes web, originalidad y copyright", "Usa fuentes y controles de originalidad de forma responsable.", "Las fuentes ayudan a comprender un tema; no deben copiarse en el manuscrito.", "Revisa personalmente datos, permisos y alertas de similitud antes de publicar."],
    "scrivere-capitoli-e-sottocapitoli": ["Cómo escribir capítulos y subcapítulos", "Redacta y revisa secciones manteniendo coherencia en todo el manuscrito.", "Cada capítulo necesita una tarea clara y un cierre que haga avanzar al lector.", "Genera con una petición precisa y usa la reelaboración solo para cambios importantes."],
    "controllare-manoscritto-prima-pubblicazione": ["Cómo revisar un manuscrito antes de publicar", "Lista práctica para revisar integridad, coherencia, vista previa y edición humana.", "Generar un manuscrito no equivale a dejarlo listo para publicar.", "Compara índice y texto, lee inicios y finales y resuelve las alertas relevantes."],
    "salvare-ripristinare-esportare-progetto-editoriale": ["Cómo guardar, restaurar y exportar un proyecto editorial", "Conserva brief, índice, secciones y fuentes mediante guardado y exportación.", "Un proyecto editorial incluye el texto, su configuración y su historial.", "Guarda después de decisiones importantes y conserva un CSV como copia completa."],
    "creare-quiz-ricette-test-prep": ["Cómo crear cuestionarios, recetas y Test Prep", "Diseña ejercicios y formatos prácticos útiles y verificables.", "El contenido interactivo debe ayudar al lector a aplicar lo aprendido.", "Indica nivel, cantidad y objetivo; después revisa variedad, respuestas y completitud."],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT o DeepSeek: qué motor elegir", "Compara motores, funciones y presupuestos en Scrittore Site.", "Elige según la tarea, funciones disponibles y presupuesto mostrado antes de empezar.", "Un brief claro y una revisión concreta aportan más valor que regenerar sin dirección."],
    "pubblicare-libro-amazon-kdp": ["Cómo preparar un libro para Amazon KDP", "Prepara, revisa y exporta un manuscrito antes de subirlo a Amazon KDP.", "Un manuscrito legible, completo y revisado debe preceder al formato y la carga.", "Revisa derechos, datos, diseño y archivo final; consulta siempre los requisitos oficiales vigentes."],
    "self-publishing-guida-pratica": ["Autoedición: de la idea a un libro listo", "Organiza proyecto, manuscrito, revisión y exportación para autopublicar.", "La autoedición mantiene al autor al frente de las decisiones creativas y editoriales.", "Usa el índice como plan, revisa con cuidado y guarda cada versión del proyecto."],
  },
  fr: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["Comment écrire un livre avec l'intelligence artificielle", "Guide pratique pour transformer une idée en projet éditorial complet avec Scrittore Site.", "Utilisez l'IA comme soutien éditorial et partez d'un lecteur, d'un objectif et d'une structure clairs.", "Définissez le résultat pour le lecteur puis relisez chaque section générée avant l'export."],
    "come-compilare-sidebar-scrittore-site": ["Comment remplir la barre latérale de Scrittore Site", "Instructions pour configurer le brief qui guide le plan et le manuscrit.", "La barre latérale transforme votre idée en consignes éditoriales cohérentes.", "Choisissez langue, genre, voix, public, périmètre et limites avant de générer le plan."],
    "creare-indice-professionale-libro": ["Comment créer un plan de livre professionnel", "Construisez et améliorez un plan sans chapitres répétitifs ni sujets hors thème.", "Un bon plan crée un parcours logique et donne une fonction distincte à chaque section.", "Gardez les thèmes essentiels, fusionnez les recouvrements et vérifiez la promesse finale."],
    "fonti-web-originalita-copyright-libro": ["Sources web, originalité et copyright", "Utilisez les sources et les contrôles d'originalité avec responsabilité.", "Les sources servent à comprendre un sujet, pas à être copiées dans le manuscrit.", "Vérifiez vous-même les faits, autorisations et alertes de similarité avant publication."],
    "scrivere-capitoli-e-sottocapitoli": ["Comment écrire chapitres et sous-chapitres", "Rédigez et révisez des sections en gardant le manuscrit cohérent.", "Chaque chapitre doit avoir une mission claire et une conclusion qui fait avancer le lecteur.", "Formulez une demande précise et utilisez la réécriture IA pour les changements importants."],
    "controllare-manoscritto-prima-pubblicazione": ["Comment contrôler un manuscrit avant publication", "Checklist pratique pour la complétude, la cohérence, l'aperçu et la relecture humaine.", "Générer un manuscrit ne signifie pas qu'il est prêt à publier.", "Comparez plan et texte, relisez débuts et fins, puis résolvez les alertes pertinentes."],
    "salvare-ripristinare-esportare-progetto-editoriale": ["Comment sauvegarder, restaurer et exporter un projet éditorial", "Conservez brief, plan, sections et sources grâce à la sauvegarde et l'export.", "Un projet éditorial comprend le texte, sa configuration et son historique.", "Sauvegardez après chaque décision importante et conservez un CSV comme copie complète."],
    "creare-quiz-ricette-test-prep": ["Comment créer quiz, recettes et Test Prep", "Concevez des exercices et formats pratiques utiles et vérifiables.", "Le contenu interactif doit aider le lecteur à appliquer ce qu'il apprend.", "Indiquez niveau, quantité et objectif, puis vérifiez variété, réponses et complétude."],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT ou DeepSeek : quel moteur choisir ?", "Comparez les moteurs IA, leurs fonctions et leurs estimations dans Scrittore Site.", "Choisissez selon la tâche, les fonctions disponibles et l'estimation affichée avant de commencer.", "Un brief clair et une relecture ciblée valent mieux que des générations répétées."],
    "pubblicare-libro-amazon-kdp": ["Comment préparer un livre pour Amazon KDP", "Préparez, contrôlez et exportez un manuscrit avant son dépôt sur Amazon KDP.", "Un manuscrit lisible, complet et vérifié doit précéder la mise en forme et le dépôt.", "Vérifiez droits, données, mise en page et fichier final; consultez les règles officielles à jour."],
    "self-publishing-guida-pratica": ["Autoédition : de l'idée au livre prêt", "Organisez projet, manuscrit, relecture et export pour publier en indépendant.", "L'autoédition garde l'auteur responsable des choix créatifs et éditoriaux.", "Utilisez le plan comme feuille de route, relisez avec soin et conservez chaque version."],
  },
  de: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["Ein Buch mit künstlicher Intelligenz schreiben", "Praxisleitfaden vom Einfall bis zum vollständigen Buchprojekt mit Scrittore Site.", "Nutzen Sie KI als redaktionelle Unterstützung und beginnen Sie mit Leser, Ziel und Struktur.", "Definieren Sie zuerst das Lesergebnis und prüfen Sie jeden erzeugten Abschnitt vor dem Export."],
    "come-compilare-sidebar-scrittore-site": ["Die Scrittore-Site-Seitenleiste ausfüllen", "Anleitung für das Briefing, das Gliederung und Manuskript steuert.", "Die Seitenleiste macht aus Ihrer Idee konsistente redaktionelle Anweisungen.", "Wählen Sie Sprache, Genre, Stimme, Zielgruppe, Umfang und Grenzen vor der Gliederung."],
    "creare-indice-professionale-libro": ["Eine professionelle Buchgliederung erstellen", "Erstellen und verbessern Sie eine Gliederung ohne Wiederholungen und Nebenthemen.", "Eine gute Gliederung schafft einen logischen Weg und eine Aufgabe für jeden Abschnitt.", "Behalten Sie nur Wesentliches, fassen Sie Überschneidungen zusammen und prüfen Sie das Buchversprechen."],
    "fonti-web-originalita-copyright-libro": ["Webquellen, Originalität und Urheberrecht", "Quellen und Originalitätsprüfungen verantwortungsvoll einsetzen.", "Quellen helfen beim Verständnis, dürfen aber nicht in das Manuskript kopiert werden.", "Prüfen Sie Fakten, Rechte und Ähnlichkeitshinweise vor der Veröffentlichung selbst."],
    "scrivere-capitoli-e-sottocapitoli": ["Kapitel und Unterkapitel schreiben", "Abschnitte schreiben und überarbeiten, ohne die Manuskriptlogik zu verlieren.", "Jedes Kapitel braucht eine klare Aufgabe und einen Abschluss, der Leser weiterführt.", "Formulieren Sie präzise Aufträge und nutzen Sie KI-Überarbeitung nur bei wesentlichen Änderungen."],
    "controllare-manoscritto-prima-pubblicazione": ["Ein Manuskript vor der Veröffentlichung prüfen", "Praktische Checkliste für Vollständigkeit, Kohärenz, Vorschau und menschliche Revision.", "Ein erzeugtes Manuskript ist noch nicht automatisch veröffentlichungsreif.", "Vergleichen Sie Gliederung und Text, lesen Sie Anfänge und Enden und lösen Sie wichtige Hinweise."],
    "salvare-ripristinare-esportare-progetto-editoriale": ["Ein Buchprojekt speichern, wiederherstellen und exportieren", "Briefing, Gliederung, Abschnitte und Quellen durch Speichern und Export sichern.", "Ein Buchprojekt umfasst Text, Konfiguration und Arbeitsverlauf.", "Speichern Sie nach wichtigen Entscheidungen und behalten Sie ein CSV als vollständige Sicherung."],
    "creare-quiz-ricette-test-prep": ["Quiz, Rezepte und Test Prep erstellen", "Entwerfen Sie nützliche und überprüfbare Übungen und Praxisformate.", "Interaktive Inhalte sollen Lesern helfen, Wissen anzuwenden.", "Nennen Sie Niveau, Menge und Ziel; prüfen Sie anschließend Vielfalt, Antworten und Vollständigkeit."],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT oder DeepSeek: Welche KI-Engine passt?", "Praktischer Vergleich von Funktionen und Kostenvoranschlägen in Scrittore Site.", "Wählen Sie nach Aufgabe, verfügbaren Funktionen und angezeigter Schätzung.", "Ein klares Briefing und gezielte Prüfung sind wertvoller als wiederholte Generierung."],
    "pubblicare-libro-amazon-kdp": ["Ein Buch für Amazon KDP vorbereiten", "Manuskript vor dem Upload zu Amazon KDP vorbereiten, prüfen und exportieren.", "Ein lesbares, vollständiges und geprüftes Manuskript kommt vor Formatierung und Upload.", "Prüfen Sie Rechte, Daten, Layout und Datei und beachten Sie aktuelle offizielle Anforderungen."],
    "self-publishing-guida-pratica": ["Self-Publishing: Von der Idee zum fertigen Buch", "Projekt, Manuskript, Revision und Export für die Selbstveröffentlichung organisieren.", "Beim Self-Publishing behält der Autor die Verantwortung für kreative und publizistische Entscheidungen.", "Nutzen Sie die Gliederung als Plan, überarbeiten Sie sorgfältig und sichern Sie jede Version."],
  },
  ro: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["Cum să scrii o carte cu inteligență artificială", "Ghid practic pentru a transforma o idee într-un proiect editorial complet.", "Folosește IA ca sprijin editorial și pornește de la cititor, obiectiv și structură clare.", "Definește rezultatul pentru cititor și verifică fiecare secțiune generată înainte de export."],
    "come-compilare-sidebar-scrittore-site": ["Cum completezi bara laterală Scrittore Site", "Instrucțiuni pentru brief-ul care ghidează cuprinsul și manuscrisul.", "Bara laterală transformă ideea în instrucțiuni editoriale coerente.", "Alege limba, genul, vocea, publicul și limitele înainte de a genera cuprinsul."],
    "creare-indice-professionale-libro": ["Cum creezi un cuprins profesional", "Creează și îmbunătățește un cuprins fără capitole repetitive.", "Un cuprins bun oferă un parcurs logic și un rol distinct fiecărei secțiuni.", "Păstrează doar temele esențiale, unește suprapunerile și verifică promisiunea finală."],
    "fonti-web-originalita-copyright-libro": ["Surse web, originalitate și drepturi de autor", "Folosește responsabil sursele și controalele de originalitate.", "Sursele ajută la înțelegerea unui subiect; nu trebuie copiate în manuscris.", "Verifică personal faptele, permisiunile și alertele de similitudine înainte de publicare."],
    "scrivere-capitoli-e-sottocapitoli": ["Cum scrii capitole și subcapitole", "Scrie și revizuiește secțiuni păstrând coerența manuscrisului.", "Fiecare capitol are nevoie de un rol clar și de o încheiere utilă cititorului.", "Cere conținut precis și folosește rescrierea IA numai pentru schimbări importante."],
    "controllare-manoscritto-prima-pubblicazione": ["Cum verifici un manuscris înainte de publicare", "Listă practică pentru completitudine, coerență, previzualizare și revizie umană.", "Generarea manuscrisului nu înseamnă că este gata de publicare.", "Compară cuprinsul cu textul, citește începuturile și finalurile și rezolvă alertele relevante."],
    "salvare-ripristinare-esportare-progetto-editoriale": ["Cum salvezi, restaurezi și exporți un proiect editorial", "Păstrează brief-ul, cuprinsul, secțiunile și sursele prin salvare și export.", "Un proiect editorial include textul, configurarea și istoricul său.", "Salvează după decizii importante și păstrează un CSV ca copie completă."],
    "creare-quiz-ricette-test-prep": ["Cum creezi quizuri, rețete și Test Prep", "Proiectează exerciții și formate practice utile și verificabile.", "Conținutul interactiv trebuie să ajute cititorul să aplice ceea ce învață.", "Indică nivelul, cantitatea și obiectivul, apoi verifică varietatea și răspunsurile."],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT sau DeepSeek: ce motor alegi?", "Comparație practică a motoarelor IA și a estimărilor din Scrittore Site.", "Alege după sarcină, funcțiile disponibile și estimarea afișată înainte de pornire.", "Un brief clar și o revizie concentrată sunt mai utile decât generările repetate."],
    "pubblicare-libro-amazon-kdp": ["Cum pregătești o carte pentru Amazon KDP", "Pregătește, verifică și exportă manuscrisul înainte de încărcarea pe Amazon KDP.", "Un manuscris lizibil, complet și verificat trebuie să existe înainte de formatare și încărcare.", "Verifică drepturile, datele, aspectul și fișierul final; consultă cerințele oficiale actuale."],
    "self-publishing-guida-pratica": ["Self-publishing: de la idee la o carte pregătită", "Organizează proiectul, manuscrisul, revizia și exportul pentru autopublicare.", "Autopublicarea păstrează autorul responsabil de deciziile creative și editoriale.", "Folosește cuprinsul ca plan, revizuiește atent și păstrează fiecare versiune."],
  },
  ru: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["Как написать книгу с искусственным интеллектом", "Практическое руководство: от идеи до полноценного издательского проекта.", "Используйте ИИ как редакторскую поддержку и начните с ясных читателя, цели и структуры.", "Сначала определите результат для читателя и проверьте каждый созданный раздел перед экспортом."],
    "come-compilare-sidebar-scrittore-site": ["Как заполнить боковую панель Scrittore Site", "Инструкции для брифа, который направляет оглавление и рукопись.", "Боковая панель превращает идею в согласованные редакторские указания.", "Выберите язык, жанр, голос, аудиторию и границы до создания оглавления."],
    "creare-indice-professionale-libro": ["Как создать профессиональное оглавление", "Создавайте и улучшайте оглавление без повторяющихся глав.", "Хорошее оглавление создаёт логичный путь и отдельную задачу для каждого раздела.", "Оставьте главное, объедините пересечения и проверьте итоговое обещание книги."],
    "fonti-web-originalita-copyright-libro": ["Веб-источники, оригинальность и авторское право", "Ответственно используйте источники и проверки оригинальности.", "Источники помогают понять тему, но их нельзя копировать в рукопись.", "Перед публикацией самостоятельно проверьте факты, разрешения и сигналы сходства."],
    "scrivere-capitoli-e-sottocapitoli": ["Как писать главы и подразделы", "Пишите и редактируйте разделы, сохраняя целостность рукописи.", "У каждой главы должна быть ясная задача и завершение, ведущее читателя дальше.", "Давайте точные запросы и используйте ИИ-переработку только для важных изменений."],
    "controllare-manoscritto-prima-pubblicazione": ["Как проверить рукопись перед публикацией", "Практический список для проверки полноты, связности, предпросмотра и человеческой редакции.", "Созданная рукопись ещё не означает готовность к публикации.", "Сравните оглавление и текст, прочитайте начала и окончания и устраните важные замечания."],
    "salvare-ripristinare-esportare-progetto-editoriale": ["Как сохранить, восстановить и экспортировать проект", "Сохраняйте бриф, оглавление, разделы и источники с помощью сохранения и экспорта.", "Издательский проект включает текст, настройки и историю работы.", "Сохраняйте после важных решений и храните CSV как полную копию."],
    "creare-quiz-ricette-test-prep": ["Как создать тесты, рецепты и Test Prep", "Создавайте полезные и проверяемые упражнения и практические форматы.", "Интерактивный контент должен помогать читателю применять знания.", "Укажите уровень, количество и цель, затем проверьте разнообразие и ответы."],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT или DeepSeek: какой движок выбрать?", "Практическое сравнение ИИ-движков и оценок в Scrittore Site.", "Выбирайте по задаче, доступным функциям и оценке до запуска.", "Ясный бриф и целевая проверка важнее повторной генерации."],
    "pubblicare-libro-amazon-kdp": ["Как подготовить книгу для Amazon KDP", "Подготовьте, проверьте и экспортируйте рукопись до загрузки в Amazon KDP.", "Читаемая, полная и проверенная рукопись должна быть готова до форматирования и загрузки.", "Проверьте права, данные, верстку и итоговый файл; изучите актуальные официальные требования."],
    "self-publishing-guida-pratica": ["Самиздат: от идеи до готовой книги", "Организуйте проект, рукопись, редактуру и экспорт для самостоятельной публикации.", "Самиздат оставляет автору ответственность за творческие и издательские решения.", "Используйте оглавление как план, тщательно редактируйте и сохраняйте каждую версию."],
  },
  ar: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["كيف تكتب كتاباً بالذكاء الاصطناعي", "دليل عملي لتحويل الفكرة إلى مشروع تحريري متكامل.", "استخدم الذكاء الاصطناعي كمساند تحريري وابدأ بقارئ وهدف وبنية واضحة.", "حدد النتيجة المطلوبة للقارئ ثم راجع كل قسم مولّد قبل التصدير."],
    "come-compilare-sidebar-scrittore-site": ["كيف تملأ الشريط الجانبي في Scrittore Site", "إرشادات لإعداد الموجز الذي يقود الفهرس والمخطوطة.", "يحوّل الشريط الجانبي فكرتك إلى تعليمات تحريرية متسقة.", "اختر اللغة والنوع والصوت والجمهور والحدود قبل إنشاء الفهرس."],
    "creare-indice-professionale-libro": ["كيف تنشئ فهرساً احترافياً للكتاب", "أنشئ وطوّر فهرساً من دون فصول مكررة أو موضوعات جانبية.", "يوفر الفهرس الجيد مساراً منطقياً ووظيفة مميزة لكل قسم.", "احتفظ بالموضوعات الأساسية وادمج التداخلات وتحقق من الوعد النهائي للكتاب."],
    "fonti-web-originalita-copyright-libro": ["مصادر الويب والأصالة وحقوق النشر", "استخدم المصادر وفحوص الأصالة بمسؤولية.", "تساعد المصادر على فهم الموضوع ولا ينبغي نسخها في المخطوطة.", "تحقق بنفسك من الحقائق والتصاريح وتنبيهات التشابه قبل النشر."],
    "scrivere-capitoli-e-sottocapitoli": ["كيف تكتب الفصول والفصول الفرعية", "اكتب وراجع الأقسام مع الحفاظ على اتساق المخطوطة.", "يحتاج كل فصل إلى مهمة واضحة وخاتمة تقود القارئ إلى الأمام.", "اكتب طلباً دقيقاً واستخدم إعادة الصياغة بالذكاء الاصطناعي للتغييرات الكبيرة فقط."],
    "controllare-manoscritto-prima-pubblicazione": ["كيف تراجع مخطوطة قبل النشر", "قائمة عملية للاكتمال والتماسك والمعاينة والمراجعة البشرية.", "إنشاء المخطوطة لا يعني أنها جاهزة للنشر.", "قارن الفهرس بالنص واقرأ البدايات والنهايات وعالج التنبيهات المهمة."],
    "salvare-ripristinare-esportare-progetto-editoriale": ["كيف تحفظ وتستعيد وتصدّر مشروعاً تحريرياً", "احفظ الموجز والفهرس والأقسام والمصادر عبر الحفظ والتصدير.", "يتضمن المشروع التحريري النص وإعداداته وسجل العمل.", "احفظ بعد القرارات المهمة واحتفظ بملف CSV كنسخة كاملة."],
    "creare-quiz-ricette-test-prep": ["كيف تنشئ اختبارات ووصفات وTest Prep", "صمم تمارين وصيغاً عملية مفيدة وقابلة للتحقق.", "يجب أن يساعد المحتوى التفاعلي القارئ على تطبيق ما يتعلمه.", "حدد المستوى والكمية والهدف ثم راجع التنوع والإجابات والاكتمال."],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT أم DeepSeek: أي محرك تختار؟", "مقارنة عملية لمحركات الذكاء الاصطناعي والتقديرات في Scrittore Site.", "اختر وفق المهمة والوظائف المتاحة والتقدير المعروض قبل البدء.", "الموجز الواضح والمراجعة المركزة أهم من التوليد المتكرر."],
    "pubblicare-libro-amazon-kdp": ["كيف تجهز كتاباً لـ Amazon KDP", "جهز المخطوطة وراجعها وصدّرها قبل رفعها إلى Amazon KDP.", "يجب أن تكون المخطوطة مقروءة وكاملة ومراجعة قبل التنسيق والرفع.", "راجع الحقوق والبيانات والتخطيط والملف النهائي واطلع على المتطلبات الرسمية الحالية."],
    "self-publishing-guida-pratica": ["النشر الذاتي: من الفكرة إلى كتاب جاهز", "نظم المشروع والمخطوطة والمراجعة والتصدير للنشر المستقل.", "يبقي النشر الذاتي المؤلف مسؤولاً عن القرارات الإبداعية والتحريرية.", "استخدم الفهرس كخطة وراجع بعناية واحفظ كل نسخة من المشروع."],
  },
  zh: {
    "scrivere-un-libro-con-intelligenza-artificiale": ["如何使用人工智能写书", "将想法转化为完整编辑项目的实用指南。", "将 AI 用作编辑辅助，并从明确的读者、目标和结构开始。", "先定义读者将获得的结果，再在导出前检查每个生成章节。"],
    "come-compilare-sidebar-scrittore-site": ["如何填写 Scrittore Site 侧栏", "配置指导目录和手稿的项目简述。", "侧栏会把您的想法转化为一致的编辑指令。", "生成目录前，请选择语言、体裁、写作声音、读者和边界。"],
    "creare-indice-professionale-libro": ["如何创建专业图书目录", "创建并改进没有重复章节或跑题内容的目录。", "好的目录提供合乎逻辑的阅读路径，并赋予每一节不同任务。", "保留核心主题，合并重叠内容，并检查最终是否兑现图书承诺。"],
    "fonti-web-originalita-copyright-libro": ["网络来源、原创性与版权", "负责任地使用来源和原创性检查。", "来源帮助理解主题，但不应复制到手稿中。", "发布前请自行核实事实、许可和相似性提示。"],
    "scrivere-capitoli-e-sottocapitoli": ["如何写章节和小节", "在保持手稿连贯性的同时撰写和修改章节。", "每一章都需要明确任务和推动读者前进的结尾。", "提出具体请求，只在重大修改时使用 AI 重写。"],
    "controllare-manoscritto-prima-pubblicazione": ["如何在发布前检查手稿", "用于检查完整性、连贯性、预览和人工修订的实用清单。", "生成手稿并不代表它已经可以发布。", "比较目录和文本，阅读开头与结尾，并解决重要提示。"],
    "salvare-ripristinare-esportare-progetto-editoriale": ["如何保存、恢复和导出编辑项目", "通过保存和导出保留项目简述、目录、章节和来源。", "编辑项目不仅包括文本，还包括配置和工作记录。", "在重要决定后保存，并将 CSV 保留为完整备份。"],
    "creare-quiz-ricette-test-prep": ["如何创建测验、食谱和 Test Prep", "设计有用且可验证的练习和实用内容。", "互动内容应帮助读者应用所学知识。", "说明水平、数量和目标，然后检查多样性、答案和完整性。"],
    "gpt-o-deepseek-per-scrivere-libro": ["GPT 还是 DeepSeek：选择哪种 AI 引擎？", "Scrittore Site 中 AI 引擎、功能和预估的实用比较。", "根据任务、可用功能和开始前显示的预估进行选择。", "清晰的简述和针对性审阅比反复生成更有价值。"],
    "pubblicare-libro-amazon-kdp": ["如何为 Amazon KDP 准备图书", "在上传至 Amazon KDP 前准备、检查并导出手稿。", "可读、完整且经过检查的手稿应先于排版和上传完成。", "检查权利、数据、版式和最终文件，并查阅最新官方要求。"],
    "self-publishing-guida-pratica": ["自助出版：从想法到成书", "为独立出版组织项目、手稿、修订和导出。", "自助出版让作者继续负责创作和出版决策。", "把目录用作路线图，认真修订并保存每个项目版本。"],
  },
};

export const resourceUi: Record<Locale, ResourceUi> = {
  it: { nav: "Risorse", eyebrow: "RISORSE GRATUITE", indexTitle: "Guide per portare la tua idea fino al libro", indexLead: "Guide pratiche per usare Scrittore Site con più metodo: configura il progetto, costruisci l'indice, scrivi, controlla e conserva ogni versione.", start: "Punti essenziali", practice: "Mettilo in pratica", practiceText: "Apri il progetto, applica un passaggio alla volta e salva ciò che hai approvato.", steps: ["Definisci il risultato per il lettore.", "Segui il percorso proposto nella guida.", "Controlla il risultato nell'editor.", "Salva una versione prima di modifiche importanti."], faqQuestion: "Questa guida sostituisce una revisione professionale?", faqAnswer: "No. È un supporto pratico: le decisioni editoriali, legali e di pubblicazione restano dell'autore.", read: "Leggi la guida", begin: "Inizia gratis con 50 crediti", all: "Tutte le risorse", continue: "CONTINUA A LEGGERE", other: "Altre guide utili", ctaTitle: "Vuoi iniziare dal tuo progetto?", ctaText: "Apri Scrittore Site e costruisci il tuo progetto editoriale passo dopo passo." },
  en: { nav: "Resources", eyebrow: "FREE RESOURCES", indexTitle: "Guides to take your idea to a book", indexLead: "Practical guides for using Scrittore Site with a clear method: configure, outline, write, review and save each version.", start: "Essential points", practice: "Put it into practice", practiceText: "Open your project, apply one step at a time and save what you approve.", steps: ["Define the reader outcome.", "Follow the guide's proposed path.", "Review the result in the editor.", "Save a version before major changes."], faqQuestion: "Does this guide replace professional review?", faqAnswer: "No. It is practical support: editorial, legal and publishing decisions remain with the author.", read: "Read the guide", begin: "Start free with 50 credits", all: "All resources", continue: "KEEP READING", other: "More useful guides", ctaTitle: "Ready to begin your project?", ctaText: "Open Scrittore Site and build your editorial project step by step." },
  es: { nav: "Recursos", eyebrow: "RECURSOS GRATUITOS", indexTitle: "Guías para llevar tu idea hasta el libro", indexLead: "Guías prácticas para usar Scrittore Site con método: configura, crea el índice, escribe, revisa y guarda cada versión.", start: "Puntos esenciales", practice: "Llévalo a la práctica", practiceText: "Abre tu proyecto, aplica un paso cada vez y guarda lo que apruebes.", steps: ["Define el resultado para el lector.", "Sigue el recorrido de la guía.", "Revisa el resultado en el editor.", "Guarda una versión antes de cambios importantes."], faqQuestion: "¿Esta guía sustituye una revisión profesional?", faqAnswer: "No. Es una ayuda práctica: las decisiones editoriales, legales y de publicación siguen siendo del autor.", read: "Leer la guía", begin: "Empieza gratis con 50 créditos", all: "Todos los recursos", continue: "SEGUIR LEYENDO", other: "Otras guías útiles", ctaTitle: "¿Quieres empezar tu proyecto?", ctaText: "Abre Scrittore Site y construye tu proyecto editorial paso a paso." },
  fr: { nav: "Ressources", eyebrow: "RESSOURCES GRATUITES", indexTitle: "Des guides pour mener votre idée jusqu'au livre", indexLead: "Guides pratiques pour utiliser Scrittore Site avec méthode : configurer, structurer, rédiger, contrôler et sauvegarder.", start: "Points essentiels", practice: "Passez à la pratique", practiceText: "Ouvrez votre projet, appliquez une étape à la fois et sauvegardez ce que vous validez.", steps: ["Définissez le résultat pour le lecteur.", "Suivez le parcours proposé.", "Contrôlez le résultat dans l'éditeur.", "Sauvegardez avant les modifications importantes."], faqQuestion: "Ce guide remplace-t-il une relecture professionnelle ?", faqAnswer: "Non. C'est une aide pratique : les décisions éditoriales, juridiques et de publication restent celles de l'auteur.", read: "Lire le guide", begin: "Commencer gratuitement avec 50 crédits", all: "Toutes les ressources", continue: "POURSUIVRE LA LECTURE", other: "Autres guides utiles", ctaTitle: "Prêt à commencer votre projet ?", ctaText: "Ouvrez Scrittore Site et construisez votre projet éditorial pas à pas." },
  de: { nav: "Ressourcen", eyebrow: "KOSTENLOSE RESSOURCEN", indexTitle: "Leitfäden von der Idee bis zum Buch", indexLead: "Praxisleitfäden für Scrittore Site: Projekt einrichten, gliedern, schreiben, prüfen und Versionen speichern.", start: "Wesentliche Punkte", practice: "In die Praxis umsetzen", practiceText: "Öffnen Sie Ihr Projekt, setzen Sie einen Schritt nach dem anderen um und speichern Sie Freigegebenes.", steps: ["Definieren Sie das Lesergebnis.", "Folgen Sie dem vorgeschlagenen Weg.", "Prüfen Sie das Ergebnis im Editor.", "Speichern Sie vor wichtigen Änderungen eine Version."], faqQuestion: "Ersetzt dieser Leitfaden ein professionelles Lektorat?", faqAnswer: "Nein. Er ist eine praktische Hilfe; redaktionelle, rechtliche und veröffentlichungsbezogene Entscheidungen bleiben beim Autor.", read: "Leitfaden lesen", begin: "Kostenlos mit 50 Credits starten", all: "Alle Ressourcen", continue: "WEITERLESEN", other: "Weitere hilfreiche Leitfäden", ctaTitle: "Möchten Sie Ihr Projekt starten?", ctaText: "Öffnen Sie Scrittore Site und bauen Sie Ihr Buchprojekt Schritt für Schritt auf." },
  ro: { nav: "Resurse", eyebrow: "RESURSE GRATUITE", indexTitle: "Ghiduri pentru a duce ideea până la carte", indexLead: "Ghiduri practice pentru Scrittore Site: configurează, creează cuprinsul, scrie, verifică și salvează fiecare versiune.", start: "Puncte esențiale", practice: "Aplică în practică", practiceText: "Deschide proiectul, aplică pașii pe rând și salvează ceea ce aprobi.", steps: ["Definește rezultatul pentru cititor.", "Urmează traseul propus.", "Verifică rezultatul în editor.", "Salvează o versiune înainte de schimbări importante."], faqQuestion: "Acest ghid înlocuiește o revizie profesională?", faqAnswer: "Nu. Este un sprijin practic; deciziile editoriale, juridice și de publicare rămân ale autorului.", read: "Citește ghidul", begin: "Începe gratuit cu 50 de credite", all: "Toate resursele", continue: "CONTINUĂ LECTURA", other: "Alte ghiduri utile", ctaTitle: "Vrei să începi proiectul?", ctaText: "Deschide Scrittore Site și construiește proiectul editorial pas cu pas." },
  ru: { nav: "Материалы", eyebrow: "БЕСПЛАТНЫЕ МАТЕРИАЛЫ", indexTitle: "Руководства: от идеи до книги", indexLead: "Практические руководства по Scrittore Site: настройте проект, создайте оглавление, напишите, проверьте и сохраните версии.", start: "Главные пункты", practice: "Примените на практике", practiceText: "Откройте проект, выполняйте шаги по очереди и сохраняйте то, что одобрили.", steps: ["Определите результат для читателя.", "Следуйте предложенному пути.", "Проверьте результат в редакторе.", "Сохраните версию перед важными изменениями."], faqQuestion: "Заменяет ли это руководство профессиональную редактуру?", faqAnswer: "Нет. Это практическая поддержка; редакторские, юридические и издательские решения остаются за автором.", read: "Читать руководство", begin: "Начать бесплатно с 50 кредитами", all: "Все материалы", continue: "ЧИТАТЬ ДАЛЬШЕ", other: "Другие полезные руководства", ctaTitle: "Готовы начать проект?", ctaText: "Откройте Scrittore Site и создавайте издательский проект шаг за шагом." },
  ar: { nav: "الموارد", eyebrow: "موارد مجانية", indexTitle: "أدلة تنقل فكرتك إلى كتاب", indexLead: "أدلة عملية لاستخدام Scrittore Site: اضبط المشروع وأنشئ الفهرس واكتب وراجع واحفظ كل نسخة.", start: "النقاط الأساسية", practice: "طبّق عملياً", practiceText: "افتح مشروعك وطبّق خطوة واحدة في كل مرة واحفظ ما توافق عليه.", steps: ["حدد النتيجة للقارئ.", "اتبع المسار المقترح في الدليل.", "راجع النتيجة في المحرر.", "احفظ نسخة قبل التغييرات المهمة."], faqQuestion: "هل يحل هذا الدليل محل المراجعة المهنية؟", faqAnswer: "لا. إنه دعم عملي، أما القرارات التحريرية والقانونية وقرارات النشر فتبقى للمؤلف.", read: "اقرأ الدليل", begin: "ابدأ مجاناً مع 50 رصيداً", all: "كل الموارد", continue: "تابع القراءة", other: "أدلة مفيدة أخرى", ctaTitle: "هل تريد بدء مشروعك؟", ctaText: "افتح Scrittore Site وابنِ مشروعك التحريري خطوة بخطوة." },
  zh: { nav: "资源", eyebrow: "免费资源", indexTitle: "从想法走向图书的指南", indexLead: "Scrittore Site 实用指南：配置项目、创建目录、写作、检查并保存每个版本。", start: "核心要点", practice: "付诸实践", practiceText: "打开您的项目，逐步执行，并保存您确认的内容。", steps: ["定义读者将获得的结果。", "遵循指南中的建议路径。", "在编辑器中检查结果。", "重大修改前保存一个版本。"], faqQuestion: "本指南能替代专业编辑吗？", faqAnswer: "不能。它提供实用支持；编辑、法律和出版决定仍由作者负责。", read: "阅读指南", begin: "免费开始，赠送 50 积分", all: "全部资源", continue: "继续阅读", other: "更多实用指南", ctaTitle: "准备开始您的项目了吗？", ctaText: "打开 Scrittore Site，逐步构建您的编辑项目。" },
};

export function getResources(locale: Locale): ResourceGuide[] {
  if (locale === "it") return resources;
  const ui = resourceUi[locale];
  return resources.map((resource) => {
    const [title, description, intro, focus] = seeds[locale][resource.slug];
    return {
      slug: resource.slug,
      title,
      description,
      keywords: [title, description, "Scrittore Site"],
      intro,
      sections: [
        { heading: ui.start, paragraphs: [intro, focus], steps: ui.steps },
        { heading: ui.practice, paragraphs: [ui.practiceText] },
      ],
      faq: [[ui.faqQuestion, ui.faqAnswer]],
    };
  });
}

export function getResource(locale: Locale, slug: string) {
  return getResources(locale).find((resource) => resource.slug === slug);
}
