export type ResourceSection = {
  heading: string;
  paragraphs: string[];
  steps?: string[];
  note?: string;
};

export type ResourceGuide = {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  intro: string;
  sections: ResourceSection[];
  faq: [string, string][];
};

export const resources: ResourceGuide[] = [
  {
    slug: "scrivere-un-libro-con-intelligenza-artificiale",
    title: "Come scrivere un libro con l'intelligenza artificiale",
    description: "Guida pratica per trasformare un'idea in un progetto editoriale completo con Scrittore Site, mantenendo il controllo su indice, testi e revisione.",
    keywords: ["scrivere un libro con intelligenza artificiale", "software per scrivere un libro", "creare un libro online", "Scrittore Site"],
    intro: "L'intelligenza artificiale è utile quando le dai un progetto chiaro e la usi come supporto editoriale, non come pilota automatico. In Scrittore Site il lavoro parte dalla tua idea, passa da una struttura verificabile e resta modificabile fino all'esportazione.",
    sections: [
      { heading: "1. Parti da un risultato concreto", paragraphs: ["Prima di aprire l'app, scrivi in una frase cosa il lettore saprà capire, fare o portare con sé alla fine. Un obiettivo come “spiegare l'HACCP a chi inizia” è più utile di “scrivere un libro sull'HACCP”, perché aiuta a scegliere argomenti, esempi e tono.", "Definisci anche il pubblico: principianti, persone già pratiche o professionisti. Questa scelta evita un testo che alterna spiegazioni troppo semplici e passaggi troppo tecnici."], steps: ["Apri Scrittore Site e scegli la lingua del manoscritto.", "Inserisci titolo provvisorio, pubblico e obiettivo del libro.", "Descrivi il risultato finale desiderato con una frase verificabile."] },
      { heading: "2. Compila la sidebar prima di generare", paragraphs: ["La sidebar è la bussola dell'intero progetto. Genere, tipologia di scrittura, stile, punto di vista, argomento e approfondimenti vengono usati insieme per costruire indice e sezioni. Compilarla bene richiede pochi minuti e riduce le rigenerazioni inutili.", "Non serve inventare dettagli: basta essere specifici su ciò che conta. Per un manuale, indica procedure, limiti e livello del lettore; per una guida di benessere, indica tono, cautele e pratiche escluse."], note: "Evita richieste contraddittorie: un testo “tecnico e analitico” con uno stile “solo narrativo” può produrre risultati meno coerenti." },
      { heading: "3. Crea e controlla l'indice", paragraphs: ["L'indice non è un passaggio burocratico: è il contratto di completezza del libro. Generarlo dopo aver definito la sidebar permette di verificare se ogni parte contribuisce davvero al risultato promesso.", "Leggilo come farebbe il lettore. Se un capitolo manca, se due voci sembrano dire la stessa cosa o se il finale non chiude il percorso, intervieni prima della stesura. Correggere la struttura costa meno che riscrivere molte sezioni."], steps: ["Genera l'indice.", "Controlla sequenza, titoli e numero di sezioni previsto.", "Usa la rigenerazione mirata solo per le parti da migliorare.", "Salva la sessione quando la struttura ti convince."] },
      { heading: "4. Scrivi, rivedi e conserva il controllo", paragraphs: ["Puoi lavorare sezione per sezione oppure avviare la stesura completa. In entrambi i casi il testo rimane nell'editor: leggilo, modifica ciò che non rappresenta la tua voce e verifica le affermazioni tecniche prima della pubblicazione.", "Alla fine usa anteprima, controllo di completezza e gli strumenti di esportazione. Word, PDF e CSV rispondono a esigenze diverse: il CSV serve anche come copia completa del progetto editoriale."], steps: ["Genera una sezione e verifica che risponda al suo titolo.", "Prosegui con le sezioni successive o con la stesura completa.", "Esegui i controlli editoriali e di originalità come supporto, non come certificazione legale.", "Esporta soltanto dopo una revisione umana del manoscritto."] },
    ],
    faq: [["Posso far scrivere tutto il libro al software?", "Sì, ma il progetto deve essere compilato e l'output va sempre letto, corretto e verificato prima della pubblicazione."], ["L'AI sostituisce l'autore?", "No. L'autore definisce il progetto, approva le scelte e rimane responsabile del testo finale."]],
  },
  {
    slug: "come-compilare-sidebar-scrittore-site",
    title: "Come compilare la sidebar di Scrittore Site",
    description: "Istruzioni chiare per compilare i campi della sidebar e ottenere un indice e un manoscritto più coerenti con il tuo progetto editoriale.",
    keywords: ["compilare sidebar Scrittore Site", "come creare un libro online", "titolo obiettivo trama libro", "generare indice libro"],
    intro: "La qualità del libro inizia dalla configurazione. La sidebar traduce la tua idea in istruzioni editoriali che il sistema può applicare in modo coerente dall'indice all'ultima sezione.",
    sections: [
      { heading: "Titolo, autore e lingua", paragraphs: ["Usa un titolo provvisorio chiaro: può cambiare in seguito, ma deve indicare il tema e il pubblico. Inserisci il nome autore che desideri vedere nel progetto. La lingua scelta deve essere quella del manoscritto, non quella dell'interfaccia.", "Se lavori su un testo multilingue, crea un progetto distinto per ogni lingua. Mescolare lingue nella stessa sidebar rende meno stabile la terminologia."], steps: ["Scrivi un titolo riconoscibile e non eccessivamente generico.", "Inserisci l'autore o lascialo da completare in seguito.", "Seleziona la lingua del libro prima della generazione."] },
      { heading: "Genere, tipologia, stile e punto di vista", paragraphs: ["Quattro scelte orientano la forma del testo. Il genere definisce la struttura attesa; la tipologia di scrittura definisce il registro; lo stile definisce il ritmo; il punto di vista regola il rapporto con il lettore.", "Per esempio, un manuale per principianti può usare Manuale Pratico, Conversazionale ed Empatico, Diretto e Pratico e Tu. Un testo rivolto a professionisti può usare Manuale Tecnico, Professionale Accademico, Tecnico e Analitico e Voi."], note: "Scegli una direzione precisa invece di tentare di usare tutti gli stili insieme." },
      { heading: "Obiettivo e risultato finale", paragraphs: ["L'obiettivo spiega perché il libro esiste. Il risultato finale descrive cosa il lettore saprà fare o comprendere. Entrambi devono essere concreti e proporzionati al genere.", "Scrivi: “Il lettore saprà preparare un piano di studio di quattro settimane e verificare i propri progressi”. Evita: “Il lettore cambierà vita” o “diventerà esperto”, perché sono promesse vaghe e non verificabili."], steps: ["Indica il problema del lettore.", "Indica il risultato pratico o conoscitivo che il libro offre.", "Controlla che il risultato sia compatibile con la lunghezza scelta."] },
      { heading: "Trama o argomento e approfondimenti", paragraphs: ["Per narrativa descrivi protagonista, conflitto, evoluzione e finale atteso. Per manuali e saggi descrivi il percorso logico: da cosa parte il lettore, quali concetti o procedure affronta e dove arriva.", "Nel campo Approfondimenti inserisci vincoli utili: esempi italiani, esercizi, avvertenze, argomenti da escludere, aggiornamento di norme o dati. Non incollare testi di terzi: usa parole tue e fornisci solo il contesto necessario."], steps: ["Elenca gli argomenti indispensabili.", "Segnala vincoli, limiti e cautele.", "Se il tema è normativo, medico, finanziario o tecnico, chiedi la verifica delle informazioni prima della pubblicazione."] },
    ],
    faq: [["Devo compilare tutti i campi?", "Sì, quando possibile: i campi della sidebar lavorano insieme e una configurazione completa migliora la coerenza."], ["Posso modificare la sidebar in seguito?", "Sì. Dopo modifiche importanti è prudente ricontrollare l'indice prima di continuare la stesura."]],
  },
  {
    slug: "creare-indice-professionale-libro",
    title: "Come creare un indice professionale per un libro",
    description: "Scopri come generare, valutare e migliorare l'indice di un libro con Scrittore Site senza creare capitoli ripetitivi o sezioni fuori tema.",
    keywords: ["creare indice libro", "indice professionale libro", "generatore indice libri", "struttura capitoli libro"],
    intro: "Un buon indice fa tre cose: accompagna il lettore in un ordine comprensibile, copre ciò che il libro promette e impedisce alle sezioni di ripetersi. Scrittore Site lo genera dalla sidebar, ma la decisione editoriale finale resta tua.",
    sections: [
      { heading: "Prima dell'indice: definisci il perimetro", paragraphs: ["Un indice diventa troppo lungo quando l'argomento è vago o quando ogni dettaglio viene trattato come capitolo autonomo. Definisci cosa il libro include e cosa lascia fuori: un manuale HACCP per piccoli esercizi non deve diventare un'enciclopedia di legislazione alimentare.", "La lunghezza impostata guida il numero massimo di sezioni. Compatto, Standard e Approfondito non sono sinonimi di qualità crescente: sono formati diversi, da scegliere in base al bisogno reale del lettore."], steps: ["Rileggi obiettivo e risultato finale.", "Segna tre-cinque temi indispensabili.", "Elimina dal brief i temi interessanti ma non necessari."] },
      { heading: "Leggi l'indice come un percorso", paragraphs: ["Controlla che le basi arrivino prima delle applicazioni, che ogni capitolo abbia una funzione diversa e che la conclusione restituisca una sintesi o un passo successivo. I titoli devono essere abbastanza specifici da promettere un contenuto, senza anticipare tutto.", "Nella narrativa il percorso segue conflitto, svolte e conseguenze; nei manuali segue concetti, procedura, esempi, errori comuni e verifica. La forma dipende dal genere scelto nella sidebar."], note: "Due titoli che si assomigliano spesso producono due testi che si assomigliano: uniscili o assegna loro compiti distinti." },
      { heading: "Usa la rigenerazione in modo mirato", paragraphs: ["Se il voto dell'indice segnala un difetto, non rigenerare per forza tutto. Individua il capitolo da correggere, descrivi il cambiamento richiesto e conserva ciò che già funziona.", "Una buona richiesta di revisione è precisa: “sostituisci la parte introduttiva duplicata con una sezione di esempi applicativi per principianti”. Una richiesta vaga come “migliora l'indice” rischia di produrre una struttura troppo simile alla precedente."], steps: ["Apri il controllo dell'indice.", "Leggi i problemi per capitolo o sottocapitolo.", "Correggi la richiesta, non solo il pulsante.", "Salva la nuova struttura quando è coerente con il brief."] },
      { heading: "Verifica la fattibilità della stesura", paragraphs: ["Prima di scrivere, chiediti se ogni sezione può essere trattata nella lunghezza prevista senza riempitivi. Se un titolo richiede troppe spiegazioni, dividilo; se richiede una sola definizione, accorpalo a una sezione vicina.", "Questo controllo protegge anche il budget: un indice equilibrato genera meno rigenerazioni e meno interventi successivi."],
    ],
    faq: [["Quante sezioni deve avere un libro?", "Dipende da formato, genere e obiettivo. Conta la copertura del percorso, non il numero più alto possibile."], ["L'indice generato è definitivo?", "No. È una proposta editoriale che puoi modificare e approvare prima della stesura."]],
  },
  {
    slug: "fonti-web-originalita-copyright-libro",
    title: "Fonti web, originalità e copyright: come usare Scrittore Site",
    description: "Come usare fonti web, mappatura concettuale e controllo di originalità in Scrittore Site per costruire un manoscritto originale e verificabile.",
    keywords: ["fonti web libro", "controllo originalità libro", "copyright manoscritto", "mappatura concettuale fonti"],
    intro: "Le fonti servono per comprendere un argomento, non per riprodurne la forma. Scrittore Site mostra un registro delle fonti trovate e le usa come base concettuale per progettare testi nuovi; questo non elimina il dovere di revisione e di verifica dei diritti.",
    sections: [
      { heading: "Che cosa fa la ricerca fonti", paragraphs: ["Quando attivi la ricerca web, il sistema raccoglie riferimenti pertinenti e costruisce una mappa concettuale: temi, definizioni, differenze, dati da verificare e punti da approfondire. L'obiettivo è aiutare indice e manoscritto a essere informati, non copiare il testo delle pagine consultate.", "Il registro delle fonti rende il percorso leggibile e permette di verificare cosa è stato considerato. Puoi rigenerare le fonti quando il tema cambia o quando vuoi una ricerca più aggiornata."], steps: ["Attiva la ricerca web soltanto se il progetto ne ha bisogno.", "Apri l'elenco delle fonti trovate e verifica la pertinenza.", "Rigenera le fonti se il brief cambia in modo sostanziale.", "Salva la sessione per conservare anche il registro fonti."] },
      { heading: "Come nasce un testo originale", paragraphs: ["Un testo originale non è una frase con qualche parola sostituita. Parte da una struttura propria, combina concetti da fonti diverse, sceglie esempi e ordine argomentativo autonomi e usa una voce coerente con il pubblico.", "Per questo è importante compilare bene sidebar e approfondimenti: sono le tue istruzioni editoriali e aiutano a creare un manoscritto distinto dalla forma delle fonti."], note: "Non caricare né chiedere di riscrivere testi protetti di cui non possiedi i diritti. Fornisci sintesi, fatti verificabili o materiale originale." },
      { heading: "Come leggere il controllo di originalità", paragraphs: ["Il controllo confronta campioni o sezioni con contenuti pubblicamente reperibili e segnala somiglianze da esaminare. È uno strumento di prevenzione editoriale, non una certificazione giuridica né una garanzia assoluta di assenza di violazioni.", "Se emerge una segnalazione, leggi la sezione interessata, valuta se il problema è un'espressione comune, un dato che richiede attribuzione o una formulazione troppo vicina a un testo esterno. Poi rielabora il contenuto intervenendo su struttura, esempi e spiegazione."], steps: ["Avvia il controllo quando il manoscritto contiene le sezioni principali.", "Apri solo le segnalazioni rilevanti, senza confondere somiglianze generiche con copia.", "Usa il pulsante di rielaborazione per le sezioni interessate e rileggile.", "Per dubbi sui diritti, chiedi consulenza a un professionista qualificato."] },
      { heading: "Controlli finali prima di pubblicare", paragraphs: ["Verifica dati, norme, percentuali, citazioni necessarie e autorizzazioni. Nel testo finale non basta non inserire URL: occorre rispettare anche i diritti su immagini, tabelle, esercizi, marchi e contenuti concessi da terzi.", "Conserva le prove dei permessi quando li hai ottenuti. Per pubblicazioni commerciali, una revisione legale o editoriale professionale è la scelta più prudente nei casi complessi."],
    ],
    faq: [["Il controllo copyright garantisce che Amazon approverà il libro?", "No. Riduce il rischio editoriale ma non sostituisce la tua verifica dei diritti né le decisioni delle piattaforme."], ["Le fonti vengono citate automaticamente nel libro?", "No. Il loro uso è concettuale; eventuali citazioni o riferimenti vanno gestiti consapevolmente dall'autore."]],
  },
  {
    slug: "scrivere-capitoli-e-sottocapitoli",
    title: "Come scrivere capitoli e sottocapitoli con Scrittore Site",
    description: "Guida alla stesura sezione per sezione, alla rigenerazione mirata e ai controlli per ottenere capitoli completi, coerenti e senza ripetizioni.",
    keywords: ["scrivere capitoli con AI", "rigenerare sezione libro", "sottocapitoli libro", "editor testo professionale"],
    intro: "La scrittura migliore nasce quando ogni sezione ha un compito chiaro. Scrittore Site può generare singole sezioni, sottocapitoli o l'intero manoscritto, ma il controllo editoriale resta più facile se procedi con un metodo.",
    sections: [
      { heading: "Scegli il ritmo di stesura", paragraphs: ["La stesura sezione per sezione è consigliata quando vuoi controllare voce, lessico e profondità mentre il libro cresce. La stesura completa è utile quando indice e brief sono già maturi e desideri una prima bozza continua.", "In entrambi i casi, il software conserva le sezioni già create e salva l'avanzamento. Non usare una rigenerazione generale per correggere un solo paragrafo: seleziona la sezione interessata."], steps: ["Apri la sezione dall'indice.", "Genera il contenuto e leggilo in relazione al titolo.", "Modifica direttamente nell'editor se la correzione è piccola.", "Usa la rielaborazione AI soltanto per un cambiamento sostanziale."] },
      { heading: "Dai istruzioni che producono testo utile", paragraphs: ["Una sezione funziona quando unisce spiegazione, esempio, conseguenza e chiusura. Se chiedi solo “approfondisci”, il risultato può diventare generico. Spiega invece cosa manca: una procedura, un caso concreto, una distinzione, una domanda di verifica o una conclusione.", "Mantieni una sola intenzione per richiesta. Per esempio: “aggiungi un esempio pratico rivolto a chi inizia, senza ripetere la definizione già presente”."], note: "Per argomenti regolati o sensibili, richiedi avvertenze proporzionate e verifica le informazioni prima della pubblicazione." },
      { heading: "Evita ripetizioni tra sezioni", paragraphs: ["Le ripetizioni nascono spesso da titoli sovrapposti. Prima di rigenerare, confronta il titolo con la sezione precedente e successiva. Se la sovrapposizione è reale, modifica l'indice o assegna alla sezione una prospettiva diversa.", "Nel manuale puoi distinguere teoria, procedura, esempio ed errore comune. Nella narrativa puoi distinguere scena, conflitto, decisione e conseguenza. Ogni parte deve far avanzare il lettore o la storia."], steps: ["Controlla il titolo e l'obiettivo della sezione.", "Leggi l'ultima frase della sezione precedente.", "Chiedi un contenuto nuovo e non una semplice riformulazione.", "Controlla l'anteprima completa dopo ogni blocco di lavoro."] },
      { heading: "Verifica la completezza prima di proseguire", paragraphs: ["Una sezione non è pronta solo perché ha raggiunto il numero di parole. Deve concludere il ragionamento, rispettare il limite di lunghezza e non lasciare elenchi o frasi sospese.", "Usa il controllo gratuito di testo completo o interrotto e gli esiti editoriali. Se la sezione è debole, rielaborala; se manca, generala; se è completa, passa alla successiva."],
    ],
    faq: [["Posso scrivere anche capitoli introduttivi e ringraziamenti?", "Sì. Le parti promesse dall'indice, incluse prefazione, ringraziamenti e conclusioni, fanno parte della verifica di completezza."], ["Cosa succede se una sezione non supera il controllo?", "Il sistema mostra la ragione e puoi riprovare o rielaborare senza cancellare le altre sezioni già salvate."]],
  },
  {
    slug: "controllare-manoscritto-prima-pubblicazione",
    title: "Come controllare un manoscritto prima della pubblicazione",
    description: "Checklist editoriale per usare controlli di completezza, coerenza, originalità, anteprima e revisione umana prima di esportare il libro.",
    keywords: ["controllo manoscritto", "revisione libro prima pubblicazione", "completezza sezioni libro", "anteprima professionale libro"],
    intro: "Generare un manoscritto non equivale a pubblicarlo. La fase di controllo serve a individuare parti mancanti, testo debole, promesse non mantenute, ripetizioni e problemi visivi prima che il file diventi definitivo.",
    sections: [
      { heading: "Controllo strutturale", paragraphs: ["Confronta l'indice con il manoscritto. Devono essere presenti tutte le sezioni promesse: prefazione, capitoli, sottocapitoli, esercizi, quiz, ricette, simulazioni, conclusione e ringraziamenti quando previsti.", "Il controllo finale di Scrittore Site segnala sezioni mancanti, deboli o complete. Trattalo come una checklist: non deve riscrivere il libro senza il tuo consenso, ma dirti dove intervenire."], steps: ["Apri il controllo finale.", "Filtra le sezioni mancanti o deboli.", "Leggi il problema associato a ciascuna sezione.", "Rielabora solo le aree che richiedono intervento."] },
      { heading: "Controllo editoriale", paragraphs: ["Leggi l'inizio e la fine di ogni capitolo: l'inizio deve dire al lettore dove si trova, la fine deve concludere o creare un ponte motivato. Cerca definizioni ripetute, esempi troppo simili, titoli promessi ma non sviluppati e cambi improvvisi di tono.", "Per Test Prep verifica quantità e separazione tra domande e soluzioni. Per ricettari verifica ingredienti, passaggi e porzioni. Per manuali verifica che istruzioni, limiti e cautele siano comprensibili."], note: "L'AI può aiutare a evidenziare problemi; la valutazione editoriale e la responsabilità della pubblicazione rimangono umane." },
      { heading: "Controllo visivo e ascolto", paragraphs: ["Apri l'anteprima in vista lettura professionale: cerca pagine troppo vuote, titoli spezzati, elenchi difficili da leggere e passaggi incoerenti. Il lettore vocale è utile per ascoltare frasi troppo lunghe, ripetizioni e transizioni poco naturali.", "Non affidarti soltanto all'occhio: ascoltare un capitolo consente di individuare subito una frase incompleta o un punto in cui il ragionamento salta."], steps: ["Scorri l'anteprima dall'inizio alla fine.", "Usa il sommario per controllare sezioni specifiche.", "Ascolta almeno i passaggi più complessi con il lettore vocale.", "Correggi nell'editor prima dell'esportazione."] },
      { heading: "Ultima verifica di dati e diritti", paragraphs: ["Controlla nomi, date, importi, norme, definizioni tecniche e informazioni sanitarie o finanziarie. Le conoscenze cambiano: un testo ben scritto può essere comunque da aggiornare.", "Esegui il controllo di originalità se hai usato fonti o affronti un tema molto trattato. Per dubbi legali, fiscali, medici o di copyright, fai verificare il manoscritto da una figura competente."],
    ],
    faq: [["Il controllo finale impedisce l'esportazione?", "Può segnalare criticità e distinguere una bozza da un progetto completo; la decisione di intervenire resta dell'utente."], ["Devo leggere tutto il manoscritto?", "Sì. I controlli accelerano la revisione ma non sostituiscono la lettura finale dell'autore o di un editor."]],
  },
  {
    slug: "salvare-ripristinare-esportare-progetto-editoriale",
    title: "Come salvare, ripristinare ed esportare un progetto editoriale",
    description: "Guida a salvataggio, recupero dell'ultima stesura e importazione/esportazione CSV, Word e PDF in Scrittore Site.",
    keywords: ["salvare progetto editoriale", "esportare libro Word PDF CSV", "ripristinare manoscritto", "backup libro online"],
    intro: "Un progetto editoriale comprende più del testo: sidebar, indice, sezioni, fonti e modifiche manuali. Scrittore Site offre strumenti per conservarne una copia e riprendere il lavoro senza ricominciare.",
    sections: [
      { heading: "Salva la sessione nei momenti importanti", paragraphs: ["Usa Salva sessione dopo aver completato la sidebar, approvato l'indice, scritto un blocco di sezioni o effettuato modifiche rilevanti. Il salvataggio conserva il progetto nel tuo account e permette di ritrovarlo con Riaggiorna all'ultima stesura.", "Durante la generazione il sistema protegge anche le sezioni già completate, così un'interruzione non dovrebbe cancellare ciò che è stato scritto fino a quel momento."], steps: ["Completa o aggiorna la sidebar.", "Premi Salva sessione.", "Dopo una modifica importante, salva di nuovo.", "In una nuova sessione usa Riaggiorna all'ultima stesura solo quando desideri richiamare il progetto salvato."] },
      { heading: "Capire reset e ripristino", paragraphs: ["Reset progetto è diverso dal logout: azzera il progetto attuale, inclusi i campi della sidebar. Usalo solo quando vuoi iniziare davvero un nuovo libro. Prima, esporta un CSV se desideri mantenere una copia portabile.", "Il pulsante Riaggiorna all'ultima stesura riporta sidebar, indice, sezioni e fonti salvate nell'ultima sessione. È utile quando l'app viene riaperta pulita dopo il login."], note: "Non usare Reset per risolvere un semplice problema di visualizzazione: prova prima Aggiorna pagina." },
      { heading: "CSV: la copia completa e trasferibile", paragraphs: ["L'esportazione CSV è pensata come archivio del progetto editoriale. Può includere i campi della sidebar, l'indice e le sezioni prodotte. Importando quel CSV nella sezione Importa / Esporta / Copyright puoi ripristinare il progetto.", "Conserva il file con un nome riconoscibile, ad esempio “titolo-libro-versione-data.csv”. Non modificarne manualmente le intestazioni se vuoi importarlo senza problemi."], steps: ["Vai a Importa / Esporta / Copyright.", "Esporta il CSV del progetto prima di modifiche molto ampie.", "Conserva il file in un luogo sicuro.", "Per ripristinare, importa lo stesso CSV e controlla sidebar, indice e sezioni."] },
      { heading: "Word e PDF per lettura e consegna", paragraphs: ["Word è utile per lavorare con un editor, impaginare o raccogliere revisioni. Il PDF è utile per leggere un'anteprima stabile e condividere una bozza. Nessuno dei due sostituisce il CSV come copia strutturata del progetto.", "Prima dell'esportazione finale, esegui la checklist editoriale e apri il file prodotto. Controlla titoli, numeri di pagina, caratteri speciali, immagini e tabelle."],
    ],
    faq: [["Il logout cancella il progetto?", "L'app si riapre pulita per sicurezza visiva; un progetto precedentemente salvato può essere richiamato con Riaggiorna all'ultima stesura."], ["Quale file devo conservare per riprendere tutto?", "Il CSV è la copia più completa per importare nuovamente sidebar, indice e sezioni."]],
  },
  {
    slug: "creare-quiz-ricette-test-prep",
    title: "Come creare quiz, ricette e Test Prep con Scrittore Site",
    description: "Istruzioni per progettare contenuti con domande, ricette, esercizi e simulazioni verificabili in Scrittore Site.",
    keywords: ["creare Test Prep", "generare quiz libro", "creare ricettario con AI", "esercizi libro"],
    intro: "Quiz, ricette, esercizi e simulazioni non sono riempitivi: devono far applicare al lettore ciò che ha imparato. Scrittore Site può supportare questi formati se li indichi in modo preciso nella sidebar e nell'indice.",
    sections: [
      { heading: "Scegli il formato giusto", paragraphs: ["Usa Test Prep quando il lettore deve allenarsi su argomenti verificabili, come nozioni, procedure o quiz d'esame. Usa un ricettario quando il risultato finale sono preparazioni eseguibili. Usa esercizi in un manuale quando il lettore deve tradurre una spiegazione in azione.", "Il genere scelto deve corrispondere al contenuto: non chiamare Test Prep un manuale con due domande alla fine. La struttura influenza indice, controlli e tipo di sezioni generate."], steps: ["Scegli il genere più vicino al risultato desiderato.", "Indica il livello del lettore.", "Specifica quantità, formato e obiettivo di quiz, ricette o esercizi."] },
      { heading: "Progetta l'indice con contenuti svolgibili", paragraphs: ["Ogni simulazione deve poter essere affrontata prima di vedere la correzione. Le domande vanno separate dalle soluzioni; gli esercizi devono contenere consegna, materiali o dati necessari e criterio di verifica.", "Per le ricette, ogni voce deve includere ingredienti, quantità, passaggi, tempi realistici e indicazioni di sicurezza o allergeni quando pertinenti. Evita formule vaghe come “cuoci quanto basta”."], note: "Per temi sanitari, alimentari o normativi, verifica sempre dati e istruzioni aggiornate prima della pubblicazione." },
      { heading: "Genera e controlla quantità e varietà", paragraphs: ["Quando usi i pulsanti dedicati, verifica che il numero prodotto corrisponda alla richiesta. Controlla anche duplicati, risposte ambigue e difficoltà incoerente. Un quiz di qualità non ripete la stessa domanda con parole diverse.", "Alterna definizioni, casi pratici, errori comuni e applicazioni. In un Test Prep, la correzione deve spiegare perché una risposta è corretta o sbagliata, quando utile."], steps: ["Genera il blocco richiesto.", "Conta quiz, ricette o esercizi.", "Cerca domande duplicate o soluzioni troppo evidenti.", "Rielabora soltanto gli elementi che non rispettano il brief."] },
      { heading: "Usa i controlli finali del genere", paragraphs: ["Prima dell'export, il controllo finale deve trovare tutti gli elementi promessi dall'indice. Se mancano quiz, ricette, soluzioni o conclusioni necessarie, il progetto va trattato come bozza da completare.", "Leggi come farebbe il destinatario reale: prova a risolvere una simulazione, segui una ricetta o completa un esercizio senza informazioni esterne non dichiarate."],
    ],
    faq: [["Il software verifica se un quiz è corretto?", "Può controllare struttura, quantità e coerenza; per informazioni tecniche o d'esame serve sempre una verifica umana aggiornata."], ["Posso mescolare manuale e quiz?", "Sì, se l'indice chiarisce il ruolo dei quiz e il genere scelto rimane coerente con il progetto."]],
  },
  {
    slug: "gpt-o-deepseek-per-scrivere-libro",
    title: "GPT o DeepSeek: quale cervello AI scegliere per il tuo libro",
    description: "Confronto pratico tra GPT-5.4 e DeepSeek V4 Pro in Scrittore Site: funzioni, fonti, preventivi e scelta del cervello AI per ogni progetto.",
    keywords: ["GPT o DeepSeek per scrivere libro", "DeepSeek V4 Pro Scrittore Site", "GPT-5.4 Scrittore Site", "crediti intelligenza artificiale libro"],
    intro: "Scrittore Site offre due cervelli AI separati. La scelta non riguarda solo il costo: cambia il tipo di elaborazione disponibile e il preventivo mostrato prima di ogni operazione. Puoi scegliere quello più adatto al progetto e al budget.",
    sections: [
      { heading: "Cosa offre GPT-5.4", paragraphs: ["GPT-5.4 è pensato per il percorso completo con funzioni avanzate, inclusi controlli editoriali, controllo copyright web e immagini quando previste. È la scelta adatta quando il progetto richiede una lavorazione ampia e vuoi usare tutti gli strumenti disponibili.", "Il preventivo in crediti viene mostrato prima dell'avvio. Leggilo sempre, soprattutto per stesure complete, rielaborazioni e controlli estesi."], },
      { heading: "Cosa offre DeepSeek V4 Pro", paragraphs: ["DeepSeek V4 Pro è disponibile per ricerca fonti, indice, scrittura e controlli, con un consumo di crediti differente. Il registro delle fonti trovate resta visibile anche quando usi questo cervello, così puoi verificare il materiale considerato.", "È una scelta utile per chi desidera un consumo più leggero nelle operazioni supportate, mantenendo sidebar, salvataggi e flusso editoriale del software."], },
      { heading: "Come scegliere senza confondersi", paragraphs: ["Scegli in base alla fase e alla complessità. Per una prima struttura o per una stesura standard puoi valutare il preventivo più conveniente. Per funzioni che richiedono il set completo, scegli il cervello che le supporta.", "Non basarti su una promessa assoluta di qualità: entrambi i risultati devono essere letti, controllati e, se necessario, rielaborati. Il miglior valore deriva da un brief chiaro e da revisioni mirate, non da rigenerazioni continue."], steps: ["Seleziona il cervello AI nella sidebar.", "Leggi il tariffario e il preventivo dell'azione.", "Conferma solo se costo e operazione sono chiari.", "Controlla il risultato e salva le parti approvate."] },
      { heading: "Crediti e gestione del progetto", paragraphs: ["I crediti vengono consumati in base all'azione e al cervello selezionato. I pacchetti acquistati sono gli stessi, ma il numero di attività realizzabili può variare. Questo è il motivo per cui il software mostra una stima prima della conferma.", "Se cambi cervello durante un progetto, conserva il brief e l'indice coerenti e verifica il nuovo preventivo. Il manoscritto non deve cambiare direzione solo perché cambia lo strumento."], note: "Tariffe, modelli e funzioni disponibili possono evolvere. Controlla sempre l'interfaccia dell'app prima di confermare un'operazione." },
    ],
    faq: [["Posso cambiare cervello durante il progetto?", "Sì, scegliendo il cervello nella sidebar e confermando il preventivo dell'operazione successiva."], ["DeepSeek usa le fonti web?", "Sì, quando la ricerca fonti è attiva, e il relativo registro può essere consultato e salvato nel progetto."]],
  },
];

export function getResource(slug: string) {
  return resources.find((resource) => resource.slug === slug);
}
