export const appUrl = "https://scrittoresite.streamlit.app/";
export const communityUrl = "https://community-fdjf.vercel.app/";
export const whatsappUrl = "https://wa.me/393282693777?text=Scrivo%20da%20Scrittore%20Site";
export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://scrittore.site";

export const locales = ["it", "en", "es", "fr", "de", "ro", "ru", "ar", "zh"] as const;
export type Locale = (typeof locales)[number];

type Copy = {
  language: string; direction?: "rtl"; locale: string; seoTitle: string; seoDescription: string;
  nav: [string, string, string, string, string];
  hero: string; lead: string; primary: string; secondary: string; demoTitle: string; demoText: string;
  fullscreen: string; flowTitle: string; flow: string[]; engineTitle: string; gpt: string; deepseek: string;
  creditNote: string; featureTitle: string; features: string[]; pricingTitle: string; pricingLead: string;
  faqTitle: string; finalTitle: string; community: string; support: string; copyright: string;
};

export const copy: Record<Locale, Copy> = {
  it: { language: "Italiano", locale: "it-IT", seoTitle: "Scrivi il tuo libro con l'intelligenza artificiale", seoDescription: "Scrittore Site ti aiuta a progettare, scrivere, controllare ed esportare il tuo libro.", nav:["Funzioni","Come funziona","Due cervelli AI","Crediti","FAQ"], hero:"Scrivi il tuo libro, con il tuo metodo.", lead:"Progetta, scrivi, controlla ed esporta il tuo manoscritto mantenendo sempre il controllo sul progetto.", primary:"Inizia gratis con 50 crediti", secondary:"Scopri come funziona", demoTitle:"Prova Scrittore Site", demoText:"Esplora l'applicazione direttamente qui oppure aprila a schermo intero.", fullscreen:"Apri Scrittore Site a schermo intero", flowTitle:"Dall'idea al libro", flow:["Idea","Sidebar guidata","Fonti e indice","Stesura","Controlli","Word, PDF o CSV"], engineTitle:"Due cervelli AI, una scelta consapevole", gpt:"Funzioni complete, controllo copyright web e immagini.", deepseek:"Ricerca fonti con registro visibile, indice, scrittura e controlli con consumo più leggero.", creditNote:"Il preventivo è mostrato prima dell'avvio. I crediti variano in base al cervello AI, alla lunghezza e alle operazioni usate.", featureTitle:"Tutto il necessario per il tuo progetto editoriale", features:["Indice professionale","Scrittura capitolo per capitolo","Controllo completezza","Originalità e copyright","Salvataggio e recupero","Editor, anteprima e lettore vocale","Importazione ed esportazione Word, PDF e CSV","Quiz, ricette e Test Prep"], pricingTitle:"Crediti chiari, utilizzo flessibile", pricingLead:"Scegli il pacchetto più adatto al tuo ritmo di lavoro.", faqTitle:"Domande frequenti", finalTitle:"La tua idea merita una struttura, non un foglio bianco.", community:"La nostra Community", support:"Contatta l'assistenza", copyright:"© Scrittore Site" },
  en: { language: "English", locale: "en-US", seoTitle:"Write your book with artificial intelligence", seoDescription:"Scrittore Site helps you plan, write, review and export your book.", nav:["Features","How it works","Two AI engines","Credits","FAQ"], hero:"Write your book, your way.", lead:"Plan, write, review and export your manuscript while staying in control of every step.", primary:"Start free with 50 credits", secondary:"See how it works", demoTitle:"Try Scrittore Site", demoText:"Explore the app here or open it in full screen.", fullscreen:"Open Scrittore Site in full screen", flowTitle:"From idea to book", flow:["Idea","Guided sidebar","Sources and outline","Writing","Checks","Word, PDF or CSV"], engineTitle:"Two AI engines, one informed choice", gpt:"Complete features, web copyright checks and image generation.", deepseek:"Source research with visible register, outlines, writing and lighter credit usage.", creditNote:"You see an estimate before starting. Credit use varies by AI engine, length and operation.", featureTitle:"Everything you need for your editorial project", features:["Professional outline","Chapter-by-chapter writing","Completeness check","Originality and copyright","Save and restore","Editor, preview and voice reader","Word, PDF and CSV import/export","Quizzes, recipes and Test Prep"], pricingTitle:"Clear credits, flexible use", pricingLead:"Choose the package that suits your pace.", faqTitle:"Frequently asked questions", finalTitle:"Your idea deserves structure, not a blank page.", community:"Our Community", support:"Contact support", copyright:"© Scrittore Site" },
  es: { language:"Español", locale:"es-ES", seoTitle:"Escribe tu libro con inteligencia artificial", seoDescription:"Scrittore Site te ayuda a planificar, escribir, revisar y exportar tu libro.", nav:["Funciones","Cómo funciona","Dos motores IA","Créditos","Preguntas"], hero:"Escribe tu libro, con tu propio método.", lead:"Planifica, escribe, revisa y exporta tu manuscrito manteniendo el control del proyecto.", primary:"Empieza gratis con 50 créditos", secondary:"Descubre cómo funciona", demoTitle:"Prueba Scrittore Site", demoText:"Explora la aplicación aquí o ábrela a pantalla completa.", fullscreen:"Abrir Scrittore Site a pantalla completa", flowTitle:"De la idea al libro", flow:["Idea","Barra guiada","Fuentes e índice","Redacción","Controles","Word, PDF o CSV"], engineTitle:"Dos motores IA, una elección consciente", gpt:"Funciones completas, control de copyright web e imágenes.", deepseek:"Investigación de fuentes visible, índice, redacción y consumo más ligero.", creditNote:"El presupuesto aparece antes de empezar. El consumo depende del motor, longitud y operación.", featureTitle:"Todo para tu proyecto editorial", features:["Índice profesional","Redacción por capítulos","Control de integridad","Originalidad y copyright","Guardar y recuperar","Editor, vista previa y lector de voz","Importar y exportar Word, PDF y CSV","Cuestionarios, recetas y Test Prep"], pricingTitle:"Créditos claros, uso flexible", pricingLead:"Elige el paquete adecuado para tu ritmo.", faqTitle:"Preguntas frecuentes", finalTitle:"Tu idea merece estructura, no una página en blanco.", community:"Nuestra Comunidad", support:"Contactar asistencia", copyright:"© Scrittore Site" },
  fr: { language:"Français", locale:"fr-FR", seoTitle:"Écrivez votre livre avec l'intelligence artificielle", seoDescription:"Scrittore Site vous aide à concevoir, rédiger, contrôler et exporter votre livre.", nav:["Fonctions","Comment ça marche","Deux IA","Crédits","FAQ"], hero:"Écrivez votre livre, à votre manière.", lead:"Concevez, rédigez, contrôlez et exportez votre manuscrit en gardant la maîtrise du projet.", primary:"Commencer gratuitement avec 50 crédits", secondary:"Découvrir le fonctionnement", demoTitle:"Essayer Scrittore Site", demoText:"Explorez l'application ici ou ouvrez-la en plein écran.", fullscreen:"Ouvrir Scrittore Site en plein écran", flowTitle:"De l'idée au livre", flow:["Idée","Barre guidée","Sources et plan","Rédaction","Contrôles","Word, PDF ou CSV"], engineTitle:"Deux IA, un choix éclairé", gpt:"Fonctions complètes, contrôle copyright web et images.", deepseek:"Recherche de sources visible, plan, rédaction et consommation plus légère.", creditNote:"Une estimation est affichée avant de commencer. La consommation dépend du moteur, de la longueur et de l'opération.", featureTitle:"Tout pour votre projet éditorial", features:["Plan professionnel","Rédaction chapitre par chapitre","Contrôle de complétude","Originalité et copyright","Sauvegarde et restauration","Éditeur, aperçu et lecteur vocal","Import/export Word, PDF et CSV","Quiz, recettes et Test Prep"], pricingTitle:"Crédits clairs, utilisation flexible", pricingLead:"Choisissez le forfait adapté à votre rythme.", faqTitle:"Questions fréquentes", finalTitle:"Votre idée mérite une structure, pas une page blanche.", community:"Notre communauté", support:"Contacter l'assistance", copyright:"© Scrittore Site" },
  de: { language:"Deutsch", locale:"de-DE", seoTitle:"Schreiben Sie Ihr Buch mit künstlicher Intelligenz", seoDescription:"Scrittore Site hilft Ihnen beim Planen, Schreiben, Prüfen und Exportieren Ihres Buches.", nav:["Funktionen","So funktioniert es","Zwei KI-Engines","Credits","FAQ"], hero:"Schreiben Sie Ihr Buch auf Ihre Weise.", lead:"Planen, schreiben, prüfen und exportieren Sie Ihr Manuskript und behalten Sie die Kontrolle.", primary:"Kostenlos mit 50 Credits starten", secondary:"So funktioniert es", demoTitle:"Scrittore Site testen", demoText:"Erkunden Sie die Anwendung hier oder öffnen Sie sie im Vollbildmodus.", fullscreen:"Scrittore Site im Vollbild öffnen", flowTitle:"Von der Idee zum Buch", flow:["Idee","Geführte Seitenleiste","Quellen und Gliederung","Schreiben","Prüfungen","Word, PDF oder CSV"], engineTitle:"Zwei KI-Engines, eine bewusste Wahl", gpt:"Alle Funktionen, Web-Copyrightprüfung und Bilder.", deepseek:"Quellenrecherche mit sichtbarem Register, Gliederung, Schreiben und geringerer Verbrauch.", creditNote:"Vor dem Start wird eine Schätzung gezeigt. Der Verbrauch hängt von Engine, Länge und Vorgang ab.", featureTitle:"Alles für Ihr Buchprojekt", features:["Professionelle Gliederung","Kapitelweise schreiben","Vollständigkeitsprüfung","Originalität und Copyright","Speichern und wiederherstellen","Editor, Vorschau und Sprachleser","Word-, PDF- und CSV-Import/Export","Quiz, Rezepte und Test Prep"], pricingTitle:"Klare Credits, flexible Nutzung", pricingLead:"Wählen Sie das Paket für Ihr Arbeitstempo.", faqTitle:"Häufige Fragen", finalTitle:"Ihre Idee verdient Struktur, keine leere Seite.", community:"Unsere Community", support:"Support kontaktieren", copyright:"© Scrittore Site" },
  ro: { language:"Română", locale:"ro-RO", seoTitle:"Scrie cartea ta cu inteligență artificială", seoDescription:"Scrittore Site te ajută să planifici, scrii, verifici și exporți cartea.", nav:["Funcții","Cum funcționează","Două motoare IA","Credite","Întrebări"], hero:"Scrie cartea ta, în felul tău.", lead:"Planifică, scrie, verifică și exportă manuscrisul păstrând controlul proiectului.", primary:"Începe gratuit cu 50 de credite", secondary:"Descoperă cum funcționează", demoTitle:"Încearcă Scrittore Site", demoText:"Explorează aplicația aici sau deschide-o pe tot ecranul.", fullscreen:"Deschide Scrittore Site pe tot ecranul", flowTitle:"De la idee la carte", flow:["Idee","Bară laterală ghidată","Surse și cuprins","Scriere","Verificări","Word, PDF sau CSV"], engineTitle:"Două motoare IA, o alegere informată", gpt:"Funcții complete, copyright web și imagini.", deepseek:"Cercetare surse cu registru vizibil, cuprins, scriere și consum mai redus.", creditNote:"Estimarea apare înainte de pornire. Consumul depinde de motor, lungime și operațiune.", featureTitle:"Tot ce ai nevoie pentru proiectul editorial", features:["Cuprins profesional","Scriere capitol cu capitol","Control de completitudine","Originalitate și copyright","Salvare și restaurare","Editor, previzualizare și cititor vocal","Import/export Word, PDF și CSV","Teste, rețete și Test Prep"], pricingTitle:"Credite clare, utilizare flexibilă", pricingLead:"Alege pachetul potrivit ritmului tău.", faqTitle:"Întrebări frecvente", finalTitle:"Ideea ta merită structură, nu o pagină goală.", community:"Comunitatea noastră", support:"Contactează asistența", copyright:"© Scrittore Site" },
  ru: { language:"Русский", locale:"ru-RU", seoTitle:"Напишите книгу с искусственным интеллектом", seoDescription:"Scrittore Site помогает спланировать, написать, проверить и экспортировать книгу.", nav:["Функции","Как это работает","Два ИИ","Кредиты","FAQ"], hero:"Напишите свою книгу своим способом.", lead:"Планируйте, пишите, проверяйте и экспортируйте рукопись, сохраняя контроль над проектом.", primary:"Начать бесплатно с 50 кредитами", secondary:"Как это работает", demoTitle:"Попробовать Scrittore Site", demoText:"Изучите приложение здесь или откройте его во весь экран.", fullscreen:"Открыть Scrittore Site во весь экран", flowTitle:"От идеи к книге", flow:["Идея","Панель с подсказками","Источники и оглавление","Написание","Проверки","Word, PDF или CSV"], engineTitle:"Два ИИ-движка, осознанный выбор", gpt:"Все функции, проверка web-copyright и изображения.", deepseek:"Поиск источников с видимым реестром, оглавление, написание и меньший расход.", creditNote:"Оценка показывается до запуска. Расход зависит от движка, длины и операции.", featureTitle:"Всё для издательского проекта", features:["Профессиональное оглавление","Написание по главам","Проверка полноты","Оригинальность и copyright","Сохранение и восстановление","Редактор, предпросмотр и озвучивание","Импорт/экспорт Word, PDF и CSV","Тесты, рецепты и Test Prep"], pricingTitle:"Понятные кредиты, гибкое использование", pricingLead:"Выберите пакет под свой ритм.", faqTitle:"Частые вопросы", finalTitle:"Ваша идея заслуживает структуры, а не пустой страницы.", community:"Наше сообщество", support:"Связаться с поддержкой", copyright:"© Scrittore Site" },
  ar: { language:"العربية", direction:"rtl", locale:"ar", seoTitle:"اكتب كتابك بالذكاء الاصطناعي", seoDescription:"يساعدك Scrittore Site على تخطيط كتابك وكتابته ومراجعته وتصديره.", nav:["الميزات","كيف يعمل","محركا الذكاء","الأرصدة","الأسئلة"], hero:"اكتب كتابك بطريقتك.", lead:"خطط واكتب وراجع وصدّر مخطوطتك مع الاحتفاظ بالتحكم الكامل بالمشروع.", primary:"ابدأ مجاناً مع 50 رصيداً", secondary:"اكتشف كيف يعمل", demoTitle:"جرّب Scrittore Site", demoText:"استكشف التطبيق هنا أو افتحه بملء الشاشة.", fullscreen:"افتح Scrittore Site بملء الشاشة", flowTitle:"من الفكرة إلى الكتاب", flow:["فكرة","شريط جانبي إرشادي","المصادر والفهرس","الكتابة","التحقق","Word أو PDF أو CSV"], engineTitle:"محركان للذكاء الاصطناعي وخيار واعٍ", gpt:"كل الميزات وفحص حقوق النشر على الويب والصور.", deepseek:"بحث مصادر بسجل ظاهر وفهرس وكتابة واستهلاك أخف.", creditNote:"يظهر التقدير قبل البدء. يعتمد الاستهلاك على المحرك والطول والعملية.", featureTitle:"كل ما تحتاجه لمشروعك التحريري", features:["فهرس احترافي","كتابة فصل بفصل","فحص الاكتمال","الأصالة وحقوق النشر","الحفظ والاستعادة","محرر ومعاينة وقارئ صوتي","استيراد وتصدير Word وPDF وCSV","اختبارات ووصفات وTest Prep"], pricingTitle:"أرصدة واضحة واستخدام مرن", pricingLead:"اختر الباقة المناسبة لسرعة عملك.", faqTitle:"أسئلة شائعة", finalTitle:"فكرتك تستحق بنية، لا صفحة فارغة.", community:"مجتمعنا", support:"اتصل بالدعم", copyright:"© Scrittore Site" },
  zh: { language:"中文", locale:"zh-CN", seoTitle:"使用人工智能写作您的图书", seoDescription:"Scrittore Site 帮助您规划、写作、检查和导出图书。", nav:["功能","工作方式","两种 AI 引擎","积分","常见问题"], hero:"用自己的方法写出您的书。", lead:"规划、写作、检查并导出手稿，同时始终掌控项目。", primary:"免费开始，赠送 50 积分", secondary:"了解工作方式", demoTitle:"试用 Scrittore Site", demoText:"在此探索应用，或以全屏方式打开。", fullscreen:"全屏打开 Scrittore Site", flowTitle:"从想法到图书", flow:["想法","引导式侧栏","资料与目录","写作","检查","Word、PDF 或 CSV"], engineTitle:"两种 AI 引擎，明智选择", gpt:"完整功能、网页版权检查与图片生成。", deepseek:"带可见记录的来源研究、目录、写作和更轻的积分消耗。", creditNote:"开始前会显示预估。积分消耗取决于 AI 引擎、长度和操作。", featureTitle:"编辑项目所需的一切", features:["专业目录","逐章写作","完整性检查","原创性与版权","保存与恢复","编辑器、预览和语音阅读器","Word、PDF 和 CSV 导入导出","测验、食谱和 Test Prep"], pricingTitle:"清晰积分，灵活使用", pricingLead:"选择适合您工作节奏的套餐。", faqTitle:"常见问题", finalTitle:"您的想法值得一套结构，而不是一张空白页。", community:"我们的社区", support:"联系支持团队", copyright:"© Scrittore Site" }
};

export const packages = [
  ["Prova", "15", "€1,00", "Per provare funzioni e piccoli interventi."],
  ["Base", "150", "€10,00", "Per un progetto breve o lavorazioni distribuite."],
  ["Creator", "375", "€25,00", "Per più progetti o una stesura articolata."],
  ["Studio", "750", "€50,00", "Per chi lavora con continuità."],
  ["Professionale", "1.500", "€100,00", "Per utilizzo intensivo o più manoscritti."],
] as const;

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}
